# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.assurance_approved_app_entry import AssuranceApprovedAppEntry

class TestAssuranceApprovedAppEntry(unittest.TestCase):
    """AssuranceApprovedAppEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssuranceApprovedAppEntry:
        """Test AssuranceApprovedAppEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssuranceApprovedAppEntry`
        """
        model = AssuranceApprovedAppEntry()
        if include_optional:
            return AssuranceApprovedAppEntry(
                active_users = 1234567891011,
                category = 'example string',
                data_sent_kbps = 123.45,
                id = 'example string',
                tool = 'example string'
            )
        else:
            return AssuranceApprovedAppEntry(
        )
        """

    def testAssuranceApprovedAppEntry(self):
        """Test AssuranceApprovedAppEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
