# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_software_rollouts_post_request import V1SoftwareRolloutsPostRequest

class TestV1SoftwareRolloutsPostRequest(unittest.TestCase):
    """V1SoftwareRolloutsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SoftwareRolloutsPostRequest:
        """Test V1SoftwareRolloutsPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SoftwareRolloutsPostRequest`
        """
        model = V1SoftwareRolloutsPostRequest()
        if include_optional:
            return V1SoftwareRolloutsPostRequest(
                rollout_config = graphiant_sdk.models.upgrade_rollout_config.upgradeRolloutConfig(
                    action = 'InstallActivate', 
                    description = 'Upgrade branch sites to release 25.4', 
                    device_ids = [
                        56
                        ], 
                    name = 'Q2 edge upgrade', 
                    release = 'Recommended', 
                    schedule = graphiant_sdk.models.upgrade_recurring_schedule.upgradeRecurringSchedule(
                        monthly = graphiant_sdk.models.upgrade_monthly_recurrence.upgradeMonthlyRecurrence(
                            date = 15, 
                            ordinal = 'Second', 
                            weekday = 'Tuesday', ), 
                        starts_at_ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        weekly = graphiant_sdk.models.upgrade_weekly_recurrence.upgradeWeeklyRecurrence(
                            interval = 2, 
                            weekday = 'Monday', ), 
                        yearly = graphiant_sdk.models.upgrade_yearly_recurrence.upgradeYearlyRecurrence(
                            date = 1, 
                            month = 3, 
                            ordinal = 'First', 
                            weekday = 'Wednesday', ), ), )
            )
        else:
            return V1SoftwareRolloutsPostRequest(
                rollout_config = graphiant_sdk.models.upgrade_rollout_config.upgradeRolloutConfig(
                    action = 'InstallActivate', 
                    description = 'Upgrade branch sites to release 25.4', 
                    device_ids = [
                        56
                        ], 
                    name = 'Q2 edge upgrade', 
                    release = 'Recommended', 
                    schedule = graphiant_sdk.models.upgrade_recurring_schedule.upgradeRecurringSchedule(
                        monthly = graphiant_sdk.models.upgrade_monthly_recurrence.upgradeMonthlyRecurrence(
                            date = 15, 
                            ordinal = 'Second', 
                            weekday = 'Tuesday', ), 
                        starts_at_ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        weekly = graphiant_sdk.models.upgrade_weekly_recurrence.upgradeWeeklyRecurrence(
                            interval = 2, 
                            weekday = 'Monday', ), 
                        yearly = graphiant_sdk.models.upgrade_yearly_recurrence.upgradeYearlyRecurrence(
                            date = 1, 
                            month = 3, 
                            ordinal = 'First', 
                            weekday = 'Wednesday', ), ), ),
        )
        """

    def testV1SoftwareRolloutsPostRequest(self):
        """Test V1SoftwareRolloutsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
