# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranet_public_vif_id_put_request import V1ExtranetPublicVifIdPutRequest

class TestV1ExtranetPublicVifIdPutRequest(unittest.TestCase):
    """V1ExtranetPublicVifIdPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetPublicVifIdPutRequest:
        """Test V1ExtranetPublicVifIdPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetPublicVifIdPutRequest`
        """
        model = V1ExtranetPublicVifIdPutRequest()
        if include_optional:
            return V1ExtranetPublicVifIdPutRequest(
                consumer_policy = graphiant_sdk.models.mana_v2_public_vif_consumer_policy.manaV2PublicVifConsumerPolicy(
                    lan_segments = [
                        graphiant_sdk.models.mana_v2_public_vif_consumer_lan_segment.manaV2PublicVifConsumerLanSegment(
                            allowed_prefixes = [
                                'example string'
                                ], 
                            service_lan_segment = 1234567891011, )
                        ], 
                    sites = graphiant_sdk.models.mana_v2_site_information.manaV2SiteInformation(
                        site_lists = [
                            1234567891011
                            ], ), ),
                producer_policy = graphiant_sdk.models.mana_v2_public_vif_producer_policy.manaV2PublicVifProducerPolicy(
                    devices = {
                        'key' : graphiant_sdk.models.mana_v2_public_vif_device.manaV2PublicVifDevice(
                            consumer_burst_size = 123, 
                            consumer_bw_site = 123, 
                            nat_pools = [
                                'example string'
                                ], )
                        }, 
                    profiles = [
                        graphiant_sdk.models.mana_v2_application_profile.manaV2ApplicationProfile(
                            port_range = 'example string', 
                            ports = [
                                123
                                ], 
                            protocol = 123, )
                        ], 
                    service_lan_segment = 1234567891011, 
                    service_name = 'example string', 
                    sites = graphiant_sdk.models.mana_v2_site_information.manaV2SiteInformation(
                        site_lists = [
                            1234567891011
                            ], ), 
                    sla = graphiant_sdk.models.mana_v2_sla_information.manaV2SlaInformation(
                        backup_circuit = 'ENUM_VALUE', 
                        class = 'ENUM_VALUE', 
                        primary_circuit = 'ENUM_VALUE', ), 
                    vifs = graphiant_sdk.models.mana_v2_public_vif.manaV2PublicVif(
                        covering_prefixes = graphiant_sdk.models.mana_v2_public_vif_dynamic.manaV2PublicVifDynamic(
                            entries = [
                                'example string'
                                ], ), 
                        fixed_prefixes = graphiant_sdk.models.mana_v2_public_vif_fixed.manaV2PublicVifFixed(), 
                        type = 'ENUM_VALUE', ), )
            )
        else:
            return V1ExtranetPublicVifIdPutRequest(
                producer_policy = graphiant_sdk.models.mana_v2_public_vif_producer_policy.manaV2PublicVifProducerPolicy(
                    devices = {
                        'key' : graphiant_sdk.models.mana_v2_public_vif_device.manaV2PublicVifDevice(
                            consumer_burst_size = 123, 
                            consumer_bw_site = 123, 
                            nat_pools = [
                                'example string'
                                ], )
                        }, 
                    profiles = [
                        graphiant_sdk.models.mana_v2_application_profile.manaV2ApplicationProfile(
                            port_range = 'example string', 
                            ports = [
                                123
                                ], 
                            protocol = 123, )
                        ], 
                    service_lan_segment = 1234567891011, 
                    service_name = 'example string', 
                    sites = graphiant_sdk.models.mana_v2_site_information.manaV2SiteInformation(
                        site_lists = [
                            1234567891011
                            ], ), 
                    sla = graphiant_sdk.models.mana_v2_sla_information.manaV2SlaInformation(
                        backup_circuit = 'ENUM_VALUE', 
                        class = 'ENUM_VALUE', 
                        primary_circuit = 'ENUM_VALUE', ), 
                    vifs = graphiant_sdk.models.mana_v2_public_vif.manaV2PublicVif(
                        covering_prefixes = graphiant_sdk.models.mana_v2_public_vif_dynamic.manaV2PublicVifDynamic(
                            entries = [
                                'example string'
                                ], ), 
                        fixed_prefixes = graphiant_sdk.models.mana_v2_public_vif_fixed.manaV2PublicVifFixed(), 
                        type = 'ENUM_VALUE', ), ),
        )
        """

    def testV1ExtranetPublicVifIdPutRequest(self):
        """Test V1ExtranetPublicVifIdPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
