# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.auth_permissions import AuthPermissions

class TestAuthPermissions(unittest.TestCase):
    """AuthPermissions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthPermissions:
        """Test AuthPermissions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthPermissions`
        """
        model = AuthPermissions()
        if include_optional:
            return AuthPermissions(
                billing_and_invoicing = 'read_write',
                licensing = 'read_write',
                order_status = 'read',
                support = 'read',
                user_and_tenant_management = 'read_write',
                asset_manager = 'read_write',
                global_services = 'read',
                network_configurations = 'read_write',
                safety_and_security = 'read_write',
                service_policies = 'read_write',
                compliance = 'read',
                developer_tools = 'read',
                insights = 'read_write',
                logs = 'read_write',
                monitoring_and_troubleshooting = 'read_write',
                reports = 'read'
            )
        else:
            return AuthPermissions(
        )
        """

    def testAuthPermissions(self):
        """Test AuthPermissions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
