# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.alertservice_zendesk_details import AlertserviceZendeskDetails

class TestAlertserviceZendeskDetails(unittest.TestCase):
    """AlertserviceZendeskDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlertserviceZendeskDetails:
        """Test AlertserviceZendeskDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlertserviceZendeskDetails`
        """
        model = AlertserviceZendeskDetails()
        if include_optional:
            return AlertserviceZendeskDetails(
                zendesk_api_token = 'example string',
                zendesk_assignee_id = 'example string',
                zendesk_base_url = 'example string',
                zendesk_email = 'example string'
            )
        else:
            return AlertserviceZendeskDetails(
                zendesk_api_token = 'example string',
                zendesk_assignee_id = 'example string',
                zendesk_base_url = 'example string',
                zendesk_email = 'example string',
        )
        """

    def testAlertserviceZendeskDetails(self):
        """Test AlertserviceZendeskDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
