# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.assurance_top_level_kpi import AssuranceTopLevelKpi

class TestAssuranceTopLevelKpi(unittest.TestCase):
    """AssuranceTopLevelKpi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssuranceTopLevelKpi:
        """Test AssuranceTopLevelKpi
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssuranceTopLevelKpi`
        """
        model = AssuranceTopLevelKpi()
        if include_optional:
            return AssuranceTopLevelKpi(
                data_transferred_kbps_metric = graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                    delta = 123.45, 
                    name = 'example string', 
                    percent = 123.45, 
                    tag = 'ENUM_VALUE', 
                    value = 123.45, ),
                shadow_ai_tools_metric = graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                    delta = 123.45, 
                    name = 'example string', 
                    percent = 123.45, 
                    tag = 'ENUM_VALUE', 
                    value = 123.45, ),
                tools_metric = graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                    delta = 123.45, 
                    name = 'example string', 
                    percent = 123.45, 
                    tag = 'ENUM_VALUE', 
                    value = 123.45, ),
                users_metric = graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                    delta = 123.45, 
                    name = 'example string', 
                    percent = 123.45, 
                    tag = 'ENUM_VALUE', 
                    value = 123.45, )
            )
        else:
            return AssuranceTopLevelKpi(
        )
        """

    def testAssuranceTopLevelKpi(self):
        """Test AssuranceTopLevelKpi"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
