# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_public_vif_gateway_centralized_nat import ManaV2PublicVifGatewayCentralizedNat

class TestManaV2PublicVifGatewayCentralizedNat(unittest.TestCase):
    """ManaV2PublicVifGatewayCentralizedNat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2PublicVifGatewayCentralizedNat:
        """Test ManaV2PublicVifGatewayCentralizedNat
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2PublicVifGatewayCentralizedNat`
        """
        model = ManaV2PublicVifGatewayCentralizedNat()
        if include_optional:
            return ManaV2PublicVifGatewayCentralizedNat(
                consumer_prefix = {
                    'key' : 'example string'
                    }
            )
        else:
            return ManaV2PublicVifGatewayCentralizedNat(
                consumer_prefix = {
                    'key' : 'example string'
                    },
        )
        """

    def testManaV2PublicVifGatewayCentralizedNat(self):
        """Test ManaV2PublicVifGatewayCentralizedNat"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
