# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_assurance_ai_adoption_summary_post_response import V2AssuranceAiAdoptionSummaryPostResponse

class TestV2AssuranceAiAdoptionSummaryPostResponse(unittest.TestCase):
    """V2AssuranceAiAdoptionSummaryPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2AssuranceAiAdoptionSummaryPostResponse:
        """Test V2AssuranceAiAdoptionSummaryPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2AssuranceAiAdoptionSummaryPostResponse`
        """
        model = V2AssuranceAiAdoptionSummaryPostResponse()
        if include_optional:
            return V2AssuranceAiAdoptionSummaryPostResponse(
                top_level_kpi = graphiant_sdk.models.assurance_top_level_kpi.assuranceTopLevelKpi(
                    data_transferred_kbps_metric = graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                        delta = 123.45, 
                        name = 'example string', 
                        percent = 123.45, 
                        tag = 'ENUM_VALUE', 
                        value = 123.45, ), 
                    shadow_ai_tools_metric = graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                        delta = 123.45, 
                        name = 'example string', 
                        percent = 123.45, 
                        tag = 'ENUM_VALUE', 
                        value = 123.45, ), 
                    tools_metric = , 
                    users_metric = , ),
                what_widget = graphiant_sdk.models.assurance_what_widget.assuranceWhatWidget(
                    bubble_categories = [
                        graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                            delta = 123.45, 
                            name = 'example string', 
                            percent = 123.45, 
                            tag = 'ENUM_VALUE', 
                            value = 123.45, )
                        ], 
                    top_tools_by_active_users = [
                        graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                            delta = 123.45, 
                            name = 'example string', 
                            percent = 123.45, 
                            tag = 'ENUM_VALUE', 
                            value = 123.45, )
                        ], 
                    top_tools_by_data_transferred = [
                        
                        ], ),
                when_widget = graphiant_sdk.models.assurance_when_widget.assuranceWhenWidget(
                    day_of_week = [
                        graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                            delta = 123.45, 
                            name = 'example string', 
                            percent = 123.45, 
                            tag = 'ENUM_VALUE', 
                            value = 123.45, )
                        ], 
                    hour_of_day = [
                        graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                            delta = 123.45, 
                            name = 'example string', 
                            percent = 123.45, 
                            tag = 'ENUM_VALUE', 
                            value = 123.45, )
                        ], 
                    monthly_active_users = [
                        
                        ], 
                    monthly_bandwidth_transferred = [
                        
                        ], ),
                where_widget = graphiant_sdk.models.assurance_where_widget.assuranceWhereWidget(
                    top_sites_by_users = [
                        graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                            delta = 123.45, 
                            name = 'example string', 
                            percent = 123.45, 
                            tag = 'ENUM_VALUE', 
                            value = 123.45, )
                        ], 
                    top_users_by_data_transferred = [
                        graphiant_sdk.models.assurance_user_definition.assuranceUserDefinition(
                            data_sent = 123.45, 
                            managed = True, 
                            sessions_day = 123.45, 
                            user = 'example string', 
                            vrf = 'example string', )
                        ], 
                    top_vrfs_by_users = [
                        graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                            delta = 123.45, 
                            name = 'example string', 
                            percent = 123.45, 
                            tag = 'ENUM_VALUE', 
                            value = 123.45, )
                        ], )
            )
        else:
            return V2AssuranceAiAdoptionSummaryPostResponse(
        )
        """

    def testV2AssuranceAiAdoptionSummaryPostResponse(self):
        """Test V2AssuranceAiAdoptionSummaryPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
