# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_pvif_id_details_get_response import V1PvifIdDetailsGetResponse

class TestV1PvifIdDetailsGetResponse(unittest.TestCase):
    """V1PvifIdDetailsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1PvifIdDetailsGetResponse:
        """Test V1PvifIdDetailsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1PvifIdDetailsGetResponse`
        """
        model = V1PvifIdDetailsGetResponse()
        if include_optional:
            return V1PvifIdDetailsGetResponse(
                advertise_all_sites = True,
                advertisement = graphiant_sdk.models.mana_v2_site_information.manaV2SiteInformation(
                    site_lists = [
                        1234567891011
                        ], 
                    sites = [
                        1234567891011
                        ], ),
                consumer_lan_segments = {
                    'key' : graphiant_sdk.models.mana_v2_public_vif_gateway_consumer_lan_devices.manaV2PublicVifGatewayConsumerLanDevices(
                        consumer_prefixes = [
                            'example string'
                            ], )
                    },
                covering_prefixes = [
                    'example string'
                    ],
                gateway_bgp_neighbors = {
                    'key' : graphiant_sdk.models.mana_v2_bgp_neighbor.manaV2BgpNeighbor(
                        address_families = [
                            graphiant_sdk.models.mana_v2_bgp_neighbor_address_family.manaV2BgpNeighborAddressFamily(
                                address_family = 'ENUM_VALUE', 
                                id = 1234567891011, 
                                inbound_policy = 'example string', 
                                outbound_policy = 'example string', )
                            ], 
                        allow_as_in = 123, 
                        as_override = True, 
                        bfd = graphiant_sdk.models.mana_v2_bfd_instance.manaV2BfdInstance(
                            enabled = True, 
                            minimum_interval = 123, 
                            multiplier = 123, ), 
                        bfd_neighbor = graphiant_sdk.models.mana_v2_bfd_neighbor.manaV2BfdNeighbor(
                            desired_minimum_tx_interval = 123, 
                            if_index = 123, 
                            interface = 'example string', 
                            last_updated = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                                nanos = 123, 
                                seconds = 1234567891011, ), 
                            local_diag = 'ENUM_VALUE', 
                            peer_address = 'example string', 
                            remote_diag = 'ENUM_VALUE', 
                            required_minimum_rx_interval = 123, 
                            segment_name = 'example string', 
                            source_address = 'example string', 
                            state = 'ENUM_VALUE', 
                            time_in_state = graphiant_sdk.models.google_protobuf_duration.googleProtobufDuration(
                                nanos = 123, 
                                seconds = 1234567891011, ), 
                            up = True, ), 
                        bgp_type = 'ENUM_VALUE', 
                        default_originate = 'ENUM_VALUE', 
                        dynamic_neighbor_peers = [
                            graphiant_sdk.models.mana_v2_bgp_dynamic_neighbor_oper_peer.manaV2BgpDynamicNeighborOperPeer(
                                last_oper_status_change = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                                    nanos = 123, 
                                    seconds = 1234567891011, ), 
                                local_address = 'example string', 
                                oper_status = True, 
                                peer_asn = 123, 
                                remote_address = 'example string', 
                                state = 'ENUM_VALUE', )
                            ], 
                        enabled = True, 
                        hold_timer = 123, 
                        id = 1234567891011, 
                        keepalive_timer = 123, 
                        local_address = 'example string', 
                        local_interface = 'example string', 
                        max_prefix = 10000, 
                        md5_password = 'example string', 
                        multi_hop = 5, 
                        peer_asn = 123, 
                        remote_address = 'example string', 
                        remove_private_as = True, 
                        send_community = True, 
                        state = 'ENUM_VALUE', 
                        time_since_last_oper_change = graphiant_sdk.models.google_protobuf_duration.googleProtobufDuration(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        up = True, )
                    },
                id = 1234567891011,
                lan_segment_id = 1234567891011,
                nat_prefix_strategy = graphiant_sdk.models.mana_v2_public_vif_gateway_nat_prefix_strategy.manaV2PublicVifGatewayNatPrefixStrategy(
                    centralized = graphiant_sdk.models.mana_v2_public_vif_gateway_centralized_nat.manaV2PublicVifGatewayCentralizedNat(
                        consumer_prefix = {
                            'key' : 'example string'
                            }, ), 
                    decentralized = graphiant_sdk.models.mana_v2_public_vif_gateway_decentralized_prefixes.manaV2PublicVifGatewayDecentralizedPrefixes(
                        prefixes = {
                            'key' : 'example string'
                            }, ), ),
                region_id = 123,
                service_name = 'example string',
                storage_provider = 'ENUM_VALUE'
            )
        else:
            return V1PvifIdDetailsGetResponse(
        )
        """

    def testV1PvifIdDetailsGetResponse(self):
        """Test V1PvifIdDetailsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
