# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_users_passwords_expire_post_request import V1UsersPasswordsExpirePostRequest

class TestV1UsersPasswordsExpirePostRequest(unittest.TestCase):
    """V1UsersPasswordsExpirePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1UsersPasswordsExpirePostRequest:
        """Test V1UsersPasswordsExpirePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1UsersPasswordsExpirePostRequest`
        """
        model = V1UsersPasswordsExpirePostRequest()
        if include_optional:
            return V1UsersPasswordsExpirePostRequest(
                user_ids = [
                    'example string'
                    ]
            )
        else:
            return V1UsersPasswordsExpirePostRequest(
                user_ids = [
                    'example string'
                    ],
        )
        """

    def testV1UsersPasswordsExpirePostRequest(self):
        """Test V1UsersPasswordsExpirePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
