# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_public_vif import ManaV2PublicVif

class TestManaV2PublicVif(unittest.TestCase):
    """ManaV2PublicVif unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2PublicVif:
        """Test ManaV2PublicVif
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2PublicVif`
        """
        model = ManaV2PublicVif()
        if include_optional:
            return ManaV2PublicVif(
                covering_prefixes = graphiant_sdk.models.mana_v2_public_vif_dynamic.manaV2PublicVifDynamic(
                    entries = [
                        'example string'
                        ], ),
                fixed_prefixes = graphiant_sdk.models.mana_v2_public_vif_fixed.manaV2PublicVifFixed(
                    entries = [
                        graphiant_sdk.models.mana_v2_public_vif_fixed_nat.manaV2PublicVifFixedNat(
                            outside_nat_prefix = 'example string', 
                            service_prefix = 'example string', )
                        ], ),
                type = 'ENUM_VALUE'
            )
        else:
            return ManaV2PublicVif(
                covering_prefixes = graphiant_sdk.models.mana_v2_public_vif_dynamic.manaV2PublicVifDynamic(
                    entries = [
                        'example string'
                        ], ),
                fixed_prefixes = graphiant_sdk.models.mana_v2_public_vif_fixed.manaV2PublicVifFixed(
                    entries = [
                        graphiant_sdk.models.mana_v2_public_vif_fixed_nat.manaV2PublicVifFixedNat(
                            outside_nat_prefix = 'example string', 
                            service_prefix = 'example string', )
                        ], ),
                type = 'ENUM_VALUE',
        )
        """

    def testManaV2PublicVif(self):
        """Test ManaV2PublicVif"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
