# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.common_billing_contract import CommonBillingContract

class TestCommonBillingContract(unittest.TestCase):
    """CommonBillingContract unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommonBillingContract:
        """Test CommonBillingContract
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommonBillingContract`
        """
        model = CommonBillingContract()
        if include_optional:
            return CommonBillingContract(
                contracted_credits = 12.34,
                expiration_date = graphiant_sdk.models.common_billing_time_period.commonBillingTimePeriod(
                    month = 123, 
                    year = 123, )
            )
        else:
            return CommonBillingContract(
        )
        """

    def testCommonBillingContract(self):
        """Test CommonBillingContract"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
