# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_public_vif_gateway_write_request import ManaV2PublicVifGatewayWriteRequest

class TestManaV2PublicVifGatewayWriteRequest(unittest.TestCase):
    """ManaV2PublicVifGatewayWriteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2PublicVifGatewayWriteRequest:
        """Test ManaV2PublicVifGatewayWriteRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2PublicVifGatewayWriteRequest`
        """
        model = ManaV2PublicVifGatewayWriteRequest()
        if include_optional:
            return ManaV2PublicVifGatewayWriteRequest(
                advertisement = graphiant_sdk.models.mana_v2_site_information.manaV2SiteInformation(
                    site_lists = [
                        1234567891011
                        ], 
                    sites = [
                        1234567891011
                        ], ),
                consumer_lan_segments = {
                    'key' : graphiant_sdk.models.mana_v2_public_vif_gateway_consumer_lan_devices.manaV2PublicVifGatewayConsumerLanDevices(
                        consumer_prefixes = [
                            'example string'
                            ], )
                    },
                covering_prefixes = [
                    'example string'
                    ],
                gateway_bgp_neighbors = {
                    'key' : graphiant_sdk.models.mana_v2_bgp_neighbor_config.manaV2BgpNeighborConfig(
                        address_families = {
                            'key' : graphiant_sdk.models.mana_v2_nullable_bgp_neighbor_address_family_config.manaV2NullableBgpNeighborAddressFamilyConfig(
                                family = graphiant_sdk.models.mana_v2_bgp_neighbor_address_family_config.manaV2BgpNeighborAddressFamilyConfig(
                                    address_family = 'ENUM_VALUE', 
                                    inbound_policy = graphiant_sdk.models.mana_v2_nullable_policy_name.manaV2NullablePolicyName(
                                        policy = 'example string', ), 
                                    outbound_policy = graphiant_sdk.models.mana_v2_nullable_policy_name.manaV2NullablePolicyName(
                                        policy = 'example string', ), ), )
                            }, 
                        allow_as_in = graphiant_sdk.models.mana_v2_nullable_allow_as_in.manaV2NullableAllowAsIn(
                            count = 123, ), 
                        as_override = True, 
                        bfd = graphiant_sdk.models.mana_v2_nullable_bfd_instance_config.manaV2NullableBfdInstanceConfig(), 
                        default_originate = 'ENUM_VALUE', 
                        ebgp_multihop_ttl = graphiant_sdk.models.mana_v2_nullable_ebgp_config.manaV2NullableEbgpConfig(
                            multi_hop = 123, ), 
                        enabled = True, 
                        hold_timer = 123, 
                        hold_timer_value = graphiant_sdk.models.mana_v2_nullable_hold_timer.manaV2NullableHoldTimer(
                            timer = 123, ), 
                        keepalive_timer = 123, 
                        keepalive_timer_value = graphiant_sdk.models.mana_v2_nullable_keep_alive_timer.manaV2NullableKeepAliveTimer(
                            timer = 123, ), 
                        local_address = 'example string', 
                        local_interface = graphiant_sdk.models.mana_v2_nullable_interface_name.manaV2NullableInterfaceName(
                            interface = 'example string', ), 
                        max_prefix_value = graphiant_sdk.models.mana_v2_nullable_max_prefix.manaV2NullableMaxPrefix(
                            max_prefix = 123, ), 
                        md5_password = graphiant_sdk.models.mana_v2_nullable_md5_password.manaV2NullableMd5Password(), 
                        peer_asn = 123, 
                        remote_address = 'example string', 
                        remove_private_as = True, 
                        send_community = True, )
                    },
                lan_segment_id = 1234567891011,
                nat_prefix_strategy = graphiant_sdk.models.mana_v2_public_vif_gateway_nat_prefix_strategy.manaV2PublicVifGatewayNatPrefixStrategy(
                    centralized = graphiant_sdk.models.mana_v2_public_vif_gateway_centralized_nat.manaV2PublicVifGatewayCentralizedNat(
                        consumer_prefix = {
                            'key' : 'example string'
                            }, ), 
                    decentralized = graphiant_sdk.models.mana_v2_public_vif_gateway_decentralized_prefixes.manaV2PublicVifGatewayDecentralizedPrefixes(
                        prefixes = {
                            'key' : 'example string'
                            }, ), ),
                region_id = 123,
                service_name = 'example string',
                storage_provider = 'ENUM_VALUE'
            )
        else:
            return ManaV2PublicVifGatewayWriteRequest(
                consumer_lan_segments = {
                    'key' : graphiant_sdk.models.mana_v2_public_vif_gateway_consumer_lan_devices.manaV2PublicVifGatewayConsumerLanDevices(
                        consumer_prefixes = [
                            'example string'
                            ], )
                    },
                gateway_bgp_neighbors = {
                    'key' : graphiant_sdk.models.mana_v2_bgp_neighbor_config.manaV2BgpNeighborConfig(
                        address_families = {
                            'key' : graphiant_sdk.models.mana_v2_nullable_bgp_neighbor_address_family_config.manaV2NullableBgpNeighborAddressFamilyConfig(
                                family = graphiant_sdk.models.mana_v2_bgp_neighbor_address_family_config.manaV2BgpNeighborAddressFamilyConfig(
                                    address_family = 'ENUM_VALUE', 
                                    inbound_policy = graphiant_sdk.models.mana_v2_nullable_policy_name.manaV2NullablePolicyName(
                                        policy = 'example string', ), 
                                    outbound_policy = graphiant_sdk.models.mana_v2_nullable_policy_name.manaV2NullablePolicyName(
                                        policy = 'example string', ), ), )
                            }, 
                        allow_as_in = graphiant_sdk.models.mana_v2_nullable_allow_as_in.manaV2NullableAllowAsIn(
                            count = 123, ), 
                        as_override = True, 
                        bfd = graphiant_sdk.models.mana_v2_nullable_bfd_instance_config.manaV2NullableBfdInstanceConfig(), 
                        default_originate = 'ENUM_VALUE', 
                        ebgp_multihop_ttl = graphiant_sdk.models.mana_v2_nullable_ebgp_config.manaV2NullableEbgpConfig(
                            multi_hop = 123, ), 
                        enabled = True, 
                        hold_timer = 123, 
                        hold_timer_value = graphiant_sdk.models.mana_v2_nullable_hold_timer.manaV2NullableHoldTimer(
                            timer = 123, ), 
                        keepalive_timer = 123, 
                        keepalive_timer_value = graphiant_sdk.models.mana_v2_nullable_keep_alive_timer.manaV2NullableKeepAliveTimer(
                            timer = 123, ), 
                        local_address = 'example string', 
                        local_interface = graphiant_sdk.models.mana_v2_nullable_interface_name.manaV2NullableInterfaceName(
                            interface = 'example string', ), 
                        max_prefix_value = graphiant_sdk.models.mana_v2_nullable_max_prefix.manaV2NullableMaxPrefix(
                            max_prefix = 123, ), 
                        md5_password = graphiant_sdk.models.mana_v2_nullable_md5_password.manaV2NullableMd5Password(), 
                        peer_asn = 123, 
                        remote_address = 'example string', 
                        remove_private_as = True, 
                        send_community = True, )
                    },
                lan_segment_id = 1234567891011,
                nat_prefix_strategy = graphiant_sdk.models.mana_v2_public_vif_gateway_nat_prefix_strategy.manaV2PublicVifGatewayNatPrefixStrategy(
                    centralized = graphiant_sdk.models.mana_v2_public_vif_gateway_centralized_nat.manaV2PublicVifGatewayCentralizedNat(
                        consumer_prefix = {
                            'key' : 'example string'
                            }, ), 
                    decentralized = graphiant_sdk.models.mana_v2_public_vif_gateway_decentralized_prefixes.manaV2PublicVifGatewayDecentralizedPrefixes(
                        prefixes = {
                            'key' : 'example string'
                            }, ), ),
                region_id = 123,
                service_name = 'example string',
                storage_provider = 'ENUM_VALUE',
        )
        """

    def testManaV2PublicVifGatewayWriteRequest(self):
        """Test ManaV2PublicVifGatewayWriteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
