# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_site_information import ManaV2SiteInformation

class TestManaV2SiteInformation(unittest.TestCase):
    """ManaV2SiteInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2SiteInformation:
        """Test ManaV2SiteInformation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2SiteInformation`
        """
        model = ManaV2SiteInformation()
        if include_optional:
            return ManaV2SiteInformation(
                site_lists = [
                    1234567891011
                    ],
                sites = [
                    1234567891011
                    ]
            )
        else:
            return ManaV2SiteInformation(
        )
        """

    def testManaV2SiteInformation(self):
        """Test ManaV2SiteInformation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
