# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_software_rollouts_schedule_post_request import V1SoftwareRolloutsSchedulePostRequest

class TestV1SoftwareRolloutsSchedulePostRequest(unittest.TestCase):
    """V1SoftwareRolloutsSchedulePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SoftwareRolloutsSchedulePostRequest:
        """Test V1SoftwareRolloutsSchedulePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SoftwareRolloutsSchedulePostRequest`
        """
        model = V1SoftwareRolloutsSchedulePostRequest()
        if include_optional:
            return V1SoftwareRolloutsSchedulePostRequest(
                failed_only = True,
                id = 42,
                ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, )
            )
        else:
            return V1SoftwareRolloutsSchedulePostRequest(
                id = 42,
        )
        """

    def testV1SoftwareRolloutsSchedulePostRequest(self):
        """Test V1SoftwareRolloutsSchedulePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
