# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_global_content_filters_post_request import V1GlobalContentFiltersPostRequest

class TestV1GlobalContentFiltersPostRequest(unittest.TestCase):
    """V1GlobalContentFiltersPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GlobalContentFiltersPostRequest:
        """Test V1GlobalContentFiltersPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GlobalContentFiltersPostRequest`
        """
        model = V1GlobalContentFiltersPostRequest()
        if include_optional:
            return V1GlobalContentFiltersPostRequest(
                config = graphiant_sdk.models.mana_v2_global_content_filter_config.manaV2GlobalContentFilterConfig(
                    lan_names = [
                        'example string'
                        ], 
                    name = 'example string', 
                    rules = [
                        graphiant_sdk.models.mana_v2_global_content_filter_rule.manaV2GlobalContentFilterRule(
                            domain_category_id = 1234567891011, 
                            exception_wildcards = [
                                'example string'
                                ], )
                        ], 
                    site_list_id = 1234567891011, 
                    use_all_sites = True, )
            )
        else:
            return V1GlobalContentFiltersPostRequest(
        )
        """

    def testV1GlobalContentFiltersPostRequest(self):
        """Test V1GlobalContentFiltersPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
