# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_ztagent_bindings_get_response import V1ZtagentBindingsGetResponse

class TestV1ZtagentBindingsGetResponse(unittest.TestCase):
    """V1ZtagentBindingsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ZtagentBindingsGetResponse:
        """Test V1ZtagentBindingsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ZtagentBindingsGetResponse`
        """
        model = V1ZtagentBindingsGetResponse()
        if include_optional:
            return V1ZtagentBindingsGetResponse(
                customer_id = 'example string',
                enterprise_id = 1234567891011,
                site_id = 'example string'
            )
        else:
            return V1ZtagentBindingsGetResponse(
        )
        """

    def testV1ZtagentBindingsGetResponse(self):
        """Test V1ZtagentBindingsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
