# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_public_vif_fixed import ManaV2PublicVifFixed

class TestManaV2PublicVifFixed(unittest.TestCase):
    """ManaV2PublicVifFixed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2PublicVifFixed:
        """Test ManaV2PublicVifFixed
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2PublicVifFixed`
        """
        model = ManaV2PublicVifFixed()
        if include_optional:
            return ManaV2PublicVifFixed(
                entries = [
                    graphiant_sdk.models.mana_v2_public_vif_fixed_nat.manaV2PublicVifFixedNat(
                        outside_nat_prefix = 'example string', 
                        service_prefix = 'example string', )
                    ]
            )
        else:
            return ManaV2PublicVifFixed(
        )
        """

    def testManaV2PublicVifFixed(self):
        """Test ManaV2PublicVifFixed"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
