# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.assurance_when_widget import AssuranceWhenWidget

class TestAssuranceWhenWidget(unittest.TestCase):
    """AssuranceWhenWidget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssuranceWhenWidget:
        """Test AssuranceWhenWidget
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssuranceWhenWidget`
        """
        model = AssuranceWhenWidget()
        if include_optional:
            return AssuranceWhenWidget(
                day_of_week = [
                    graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                        delta = 123.45, 
                        name = 'example string', 
                        percent = 123.45, 
                        tag = 'ENUM_VALUE', 
                        value = 123.45, )
                    ],
                hour_of_day = [
                    graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                        delta = 123.45, 
                        name = 'example string', 
                        percent = 123.45, 
                        tag = 'ENUM_VALUE', 
                        value = 123.45, )
                    ],
                monthly_active_users = [
                    graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                        delta = 123.45, 
                        name = 'example string', 
                        percent = 123.45, 
                        tag = 'ENUM_VALUE', 
                        value = 123.45, )
                    ],
                monthly_bandwidth_transferred = [
                    graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                        delta = 123.45, 
                        name = 'example string', 
                        percent = 123.45, 
                        tag = 'ENUM_VALUE', 
                        value = 123.45, )
                    ]
            )
        else:
            return AssuranceWhenWidget(
        )
        """

    def testAssuranceWhenWidget(self):
        """Test AssuranceWhenWidget"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
