# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.upgrade_yearly_recurrence import UpgradeYearlyRecurrence

class TestUpgradeYearlyRecurrence(unittest.TestCase):
    """UpgradeYearlyRecurrence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpgradeYearlyRecurrence:
        """Test UpgradeYearlyRecurrence
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpgradeYearlyRecurrence`
        """
        model = UpgradeYearlyRecurrence()
        if include_optional:
            return UpgradeYearlyRecurrence(
                var_date = 1,
                month = 3,
                ordinal = 'First',
                weekday = 'Wednesday'
            )
        else:
            return UpgradeYearlyRecurrence(
                month = 3,
        )
        """

    def testUpgradeYearlyRecurrence(self):
        """Test UpgradeYearlyRecurrence"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
