# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.assurance_where_widget import AssuranceWhereWidget

class TestAssuranceWhereWidget(unittest.TestCase):
    """AssuranceWhereWidget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssuranceWhereWidget:
        """Test AssuranceWhereWidget
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssuranceWhereWidget`
        """
        model = AssuranceWhereWidget()
        if include_optional:
            return AssuranceWhereWidget(
                top_sites_by_users = [
                    graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                        delta = 123.45, 
                        name = 'example string', 
                        percent = 123.45, 
                        tag = 'ENUM_VALUE', 
                        value = 123.45, )
                    ],
                top_users_by_data_transferred = [
                    graphiant_sdk.models.assurance_user_definition.assuranceUserDefinition(
                        data_sent = 123.45, 
                        managed = True, 
                        sessions_day = 123.45, 
                        user = 'example string', 
                        vrf = 'example string', )
                    ],
                top_vrfs_by_users = [
                    graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                        delta = 123.45, 
                        name = 'example string', 
                        percent = 123.45, 
                        tag = 'ENUM_VALUE', 
                        value = 123.45, )
                    ]
            )
        else:
            return AssuranceWhereWidget(
        )
        """

    def testAssuranceWhereWidget(self):
        """Test AssuranceWhereWidget"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
