# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.conceal_agent import ConcealAgent

class TestConcealAgent(unittest.TestCase):
    """ConcealAgent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConcealAgent:
        """Test ConcealAgent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConcealAgent`
        """
        model = ConcealAgent()
        if include_optional:
            return ConcealAgent(
                created_at = 'example string',
                disabled = True,
                id = 'example string',
                identifier = 'example string',
                last_checkin = 'example string',
                machine = 'example string'
            )
        else:
            return ConcealAgent(
        )
        """

    def testConcealAgent(self):
        """Test ConcealAgent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
