# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.statsmon_extranet_service_health import StatsmonExtranetServiceHealth

class TestStatsmonExtranetServiceHealth(unittest.TestCase):
    """StatsmonExtranetServiceHealth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsmonExtranetServiceHealth:
        """Test StatsmonExtranetServiceHealth
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsmonExtranetServiceHealth`
        """
        model = StatsmonExtranetServiceHealth()
        if include_optional:
            return StatsmonExtranetServiceHealth(
                customer_name = 'Customer 1',
                customer_prefix_health = graphiant_sdk.models.statsmon_extranet_prefix_health.statsmonExtranetPrefixHealth(
                    health = 'Impaired', 
                    missing_prefixes = [
                        '192.168.0.0/16'
                        ], ),
                overall_health = 'Impaired',
                producer_prefix_health = graphiant_sdk.models.statsmon_extranet_prefix_health.statsmonExtranetPrefixHealth(
                    health = 'Impaired', 
                    missing_prefixes = [
                        '192.168.0.0/16'
                        ], )
            )
        else:
            return StatsmonExtranetServiceHealth(
        )
        """

    def testStatsmonExtranetServiceHealth(self):
        """Test StatsmonExtranetServiceHealth"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
