# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.common_billing_time_period import CommonBillingTimePeriod

class TestCommonBillingTimePeriod(unittest.TestCase):
    """CommonBillingTimePeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommonBillingTimePeriod:
        """Test CommonBillingTimePeriod
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommonBillingTimePeriod`
        """
        model = CommonBillingTimePeriod()
        if include_optional:
            return CommonBillingTimePeriod(
                month = 123,
                year = 123
            )
        else:
            return CommonBillingTimePeriod(
        )
        """

    def testCommonBillingTimePeriod(self):
        """Test CommonBillingTimePeriod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
