# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_regions_region_id_gateways_get_response_gateway import V1RegionsRegionIdGatewaysGetResponseGateway

class TestV1RegionsRegionIdGatewaysGetResponseGateway(unittest.TestCase):
    """V1RegionsRegionIdGatewaysGetResponseGateway unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1RegionsRegionIdGatewaysGetResponseGateway:
        """Test V1RegionsRegionIdGatewaysGetResponseGateway
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1RegionsRegionIdGatewaysGetResponseGateway`
        """
        model = V1RegionsRegionIdGatewaysGetResponseGateway()
        if include_optional:
            return V1RegionsRegionIdGatewaysGetResponseGateway(
                device_id = 1234567891011,
                hostname = 'example string'
            )
        else:
            return V1RegionsRegionIdGatewaysGetResponseGateway(
        )
        """

    def testV1RegionsRegionIdGatewaysGetResponseGateway(self):
        """Test V1RegionsRegionIdGatewaysGetResponseGateway"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
