# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_public_vif_fixed_nat import ManaV2PublicVifFixedNat

class TestManaV2PublicVifFixedNat(unittest.TestCase):
    """ManaV2PublicVifFixedNat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2PublicVifFixedNat:
        """Test ManaV2PublicVifFixedNat
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2PublicVifFixedNat`
        """
        model = ManaV2PublicVifFixedNat()
        if include_optional:
            return ManaV2PublicVifFixedNat(
                outside_nat_prefix = 'example string',
                service_prefix = 'example string'
            )
        else:
            return ManaV2PublicVifFixedNat(
        )
        """

    def testManaV2PublicVifFixedNat(self):
        """Test ManaV2PublicVifFixedNat"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
