# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_lan_segment_sites_map import ManaV2LanSegmentSitesMap

class TestManaV2LanSegmentSitesMap(unittest.TestCase):
    """ManaV2LanSegmentSitesMap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2LanSegmentSitesMap:
        """Test ManaV2LanSegmentSitesMap
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2LanSegmentSitesMap`
        """
        model = ManaV2LanSegmentSitesMap()
        if include_optional:
            return ManaV2LanSegmentSitesMap(
                site_ids = {
                    'key' : graphiant_sdk.models.mana_v2_site_lan_segment_device_buckets.manaV2SiteLanSegmentDeviceBuckets(
                        lan_segment_exists = [
                            graphiant_sdk.models.mana_v2_site_device_summary.manaV2SiteDeviceSummary(
                                device_id = 12345678910, 
                                hostname = 'example string', )
                            ], 
                        lan_segment_missing = [
                            graphiant_sdk.models.mana_v2_site_device_summary.manaV2SiteDeviceSummary(
                                device_id = 12345678910, 
                                hostname = 'example string', )
                            ], )
                    },
                site_list_ids = {
                    'key' : graphiant_sdk.models.mana_v2_site_lan_segment_device_buckets.manaV2SiteLanSegmentDeviceBuckets(
                        lan_segment_exists = [
                            graphiant_sdk.models.mana_v2_site_device_summary.manaV2SiteDeviceSummary(
                                device_id = 12345678910, 
                                hostname = 'example string', )
                            ], 
                        lan_segment_missing = [
                            graphiant_sdk.models.mana_v2_site_device_summary.manaV2SiteDeviceSummary(
                                device_id = 12345678910, 
                                hostname = 'example string', )
                            ], )
                    }
            )
        else:
            return ManaV2LanSegmentSitesMap(
        )
        """

    def testManaV2LanSegmentSitesMap(self):
        """Test ManaV2LanSegmentSitesMap"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
