# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_global_content_filters_post_response import V1GlobalContentFiltersPostResponse

class TestV1GlobalContentFiltersPostResponse(unittest.TestCase):
    """V1GlobalContentFiltersPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GlobalContentFiltersPostResponse:
        """Test V1GlobalContentFiltersPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GlobalContentFiltersPostResponse`
        """
        model = V1GlobalContentFiltersPostResponse()
        if include_optional:
            return V1GlobalContentFiltersPostResponse(
                global_content_filter_id = 1234567891011
            )
        else:
            return V1GlobalContentFiltersPostResponse(
        )
        """

    def testV1GlobalContentFiltersPostResponse(self):
        """Test V1GlobalContentFiltersPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
