# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.iam_failed_user import IamFailedUser

class TestIamFailedUser(unittest.TestCase):
    """IamFailedUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IamFailedUser:
        """Test IamFailedUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IamFailedUser`
        """
        model = IamFailedUser()
        if include_optional:
            return IamFailedUser(
                reason = 'example string',
                user_id = 'example string'
            )
        else:
            return IamFailedUser(
        )
        """

    def testIamFailedUser(self):
        """Test IamFailedUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
