# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_global_domain_categories_get_response import V1GlobalDomainCategoriesGetResponse

class TestV1GlobalDomainCategoriesGetResponse(unittest.TestCase):
    """V1GlobalDomainCategoriesGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GlobalDomainCategoriesGetResponse:
        """Test V1GlobalDomainCategoriesGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GlobalDomainCategoriesGetResponse`
        """
        model = V1GlobalDomainCategoriesGetResponse()
        if include_optional:
            return V1GlobalDomainCategoriesGetResponse(
                domain_categories = [
                    graphiant_sdk.models.mana_v2_domain_category.manaV2DomainCategory(
                        description = 'example string', 
                        id = 1234567891011, 
                        name = 'example string', 
                        type = 'example string', )
                    ]
            )
        else:
            return V1GlobalDomainCategoriesGetResponse(
        )
        """

    def testV1GlobalDomainCategoriesGetResponse(self):
        """Test V1GlobalDomainCategoriesGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
