# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_regions_region_id_gateways_get_response import V1RegionsRegionIdGatewaysGetResponse

class TestV1RegionsRegionIdGatewaysGetResponse(unittest.TestCase):
    """V1RegionsRegionIdGatewaysGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1RegionsRegionIdGatewaysGetResponse:
        """Test V1RegionsRegionIdGatewaysGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1RegionsRegionIdGatewaysGetResponse`
        """
        model = V1RegionsRegionIdGatewaysGetResponse()
        if include_optional:
            return V1RegionsRegionIdGatewaysGetResponse(
                gateways = [
                    graphiant_sdk.models.v1_regions_region_id_gateways_get_response_gateway.v1RegionsRegionIdGatewaysGetResponseGateway(
                        device_id = 1234567891011, 
                        hostname = 'example string', )
                    ]
            )
        else:
            return V1RegionsRegionIdGatewaysGetResponse(
        )
        """

    def testV1RegionsRegionIdGatewaysGetResponse(self):
        """Test V1RegionsRegionIdGatewaysGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
