# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_global_content_filter_rule import ManaV2GlobalContentFilterRule

class TestManaV2GlobalContentFilterRule(unittest.TestCase):
    """ManaV2GlobalContentFilterRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2GlobalContentFilterRule:
        """Test ManaV2GlobalContentFilterRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2GlobalContentFilterRule`
        """
        model = ManaV2GlobalContentFilterRule()
        if include_optional:
            return ManaV2GlobalContentFilterRule(
                domain_category_id = 1234567891011,
                exception_wildcards = [
                    'example string'
                    ]
            )
        else:
            return ManaV2GlobalContentFilterRule(
        )
        """

    def testManaV2GlobalContentFilterRule(self):
        """Test ManaV2GlobalContentFilterRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
