# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_nullable_ma_csec_replay_protection_window_size import ManaV2NullableMaCsecReplayProtectionWindowSize

class TestManaV2NullableMaCsecReplayProtectionWindowSize(unittest.TestCase):
    """ManaV2NullableMaCsecReplayProtectionWindowSize unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2NullableMaCsecReplayProtectionWindowSize:
        """Test ManaV2NullableMaCsecReplayProtectionWindowSize
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2NullableMaCsecReplayProtectionWindowSize`
        """
        model = ManaV2NullableMaCsecReplayProtectionWindowSize()
        if include_optional:
            return ManaV2NullableMaCsecReplayProtectionWindowSize(
                replay_protection_window_size = 1234567891011
            )
        else:
            return ManaV2NullableMaCsecReplayProtectionWindowSize(
        )
        """

    def testManaV2NullableMaCsecReplayProtectionWindowSize(self):
        """Test ManaV2NullableMaCsecReplayProtectionWindowSize"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
