# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranet_public_vif_check_post_response import V1ExtranetPublicVifCheckPostResponse

class TestV1ExtranetPublicVifCheckPostResponse(unittest.TestCase):
    """V1ExtranetPublicVifCheckPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetPublicVifCheckPostResponse:
        """Test V1ExtranetPublicVifCheckPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetPublicVifCheckPostResponse`
        """
        model = V1ExtranetPublicVifCheckPostResponse()
        if include_optional:
            return V1ExtranetPublicVifCheckPostResponse(
                consumer_policy = graphiant_sdk.models.mana_v2_public_vif_consumer_policy_response.manaV2PublicVifConsumerPolicyResponse(
                    consumer_service_id = 1234567891011, 
                    lan_segments = [
                        graphiant_sdk.models.mana_v2_public_vif_consumer_lan_segment_response.manaV2PublicVifConsumerLanSegmentResponse(
                            allowed_prefixes = [
                                'example string'
                                ], 
                            outbound_security_rules = [
                                graphiant_sdk.models.mana_v2_security_policy_rule.manaV2SecurityPolicyRule(
                                    action = 'ENUM_VALUE', 
                                    implicit = True, 
                                    match = graphiant_sdk.models.mana_v2_policy_match.manaV2PolicyMatch(
                                        destination_port = 123, 
                                        destination_prefix = 'example string', 
                                        icmp_type = 123, 
                                        protocol = 123, 
                                        source_port = 123, 
                                        source_prefix = 'example string', ), 
                                    policy_rule_index = 1234567891011, 
                                    seq = 123, )
                                ], 
                            service_lan_segment = 1234567891011, 
                            traffic_rules = [
                                graphiant_sdk.models.mana_v2_traffic_policy_rule.manaV2TrafficPolicyRule(
                                    action = graphiant_sdk.models.mana_v2_traffic_policy_action.manaV2TrafficPolicyAction(
                                        backup = 'ENUM_VALUE', 
                                        class = 'ENUM_VALUE', 
                                        primary = 'ENUM_VALUE', 
                                        result = 'ENUM_VALUE', ), 
                                    policy_rule_index = 1234567891011, 
                                    seq = 123, )
                                ], )
                        ], 
                    sites = graphiant_sdk.models.mana_v2_site_information.manaV2SiteInformation(
                        site_lists = [
                            1234567891011
                            ], ), ),
                id = 1234567891011,
                producer_policy = graphiant_sdk.models.mana_v2_public_vif_producer_policy_response.manaV2PublicVifProducerPolicyResponse(
                    devices = {
                        'key' : graphiant_sdk.models.mana_v2_public_vif_device.manaV2PublicVifDevice(
                            consumer_burst_size = 123, 
                            consumer_bw_site = 123, 
                            nat_pools = [
                                'example string'
                                ], )
                        }, 
                    inbound_security_rules = [
                        graphiant_sdk.models.mana_v2_security_policy_rule.manaV2SecurityPolicyRule(
                            action = 'ENUM_VALUE', 
                            implicit = True, 
                            match = graphiant_sdk.models.mana_v2_policy_match.manaV2PolicyMatch(
                                destination_port = 123, 
                                destination_prefix = 'example string', 
                                icmp_type = 123, 
                                protocol = 123, 
                                source_port = 123, 
                                source_prefix = 'example string', ), 
                            policy_rule_index = 1234567891011, 
                            seq = 123, )
                        ], 
                    profiles = [
                        graphiant_sdk.models.mana_v2_application_profile.manaV2ApplicationProfile(
                            port_range = 'example string', 
                            ports = [
                                123
                                ], 
                            protocol = 123, )
                        ], 
                    service_lan_segment = 1234567891011, 
                    service_name = 'example string', 
                    sites = graphiant_sdk.models.mana_v2_site_information.manaV2SiteInformation(
                        site_lists = [
                            1234567891011
                            ], ), 
                    sla = graphiant_sdk.models.mana_v2_sla_information.manaV2SlaInformation(
                        backup_circuit = 'ENUM_VALUE', 
                        class = 'ENUM_VALUE', 
                        primary_circuit = 'ENUM_VALUE', ), 
                    traffic_rules = [
                        graphiant_sdk.models.mana_v2_traffic_policy_rule.manaV2TrafficPolicyRule(
                            action = graphiant_sdk.models.mana_v2_traffic_policy_action.manaV2TrafficPolicyAction(
                                backup = 'ENUM_VALUE', 
                                class = 'ENUM_VALUE', 
                                primary = 'ENUM_VALUE', 
                                result = 'ENUM_VALUE', ), 
                            policy_rule_index = 1234567891011, 
                            seq = 123, )
                        ], 
                    vifs = graphiant_sdk.models.mana_v2_public_vif.manaV2PublicVif(
                        covering_prefixes = graphiant_sdk.models.mana_v2_public_vif_dynamic.manaV2PublicVifDynamic(
                            entries = [
                                'example string'
                                ], ), 
                        fixed_prefixes = graphiant_sdk.models.mana_v2_public_vif_fixed.manaV2PublicVifFixed(), 
                        type = 'ENUM_VALUE', ), ),
                service_name = 'example string',
                type = 'ENUM_VALUE'
            )
        else:
            return V1ExtranetPublicVifCheckPostResponse(
        )
        """

    def testV1ExtranetPublicVifCheckPostResponse(self):
        """Test V1ExtranetPublicVifCheckPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
