# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_global_content_filters_get_response import V1GlobalContentFiltersGetResponse

class TestV1GlobalContentFiltersGetResponse(unittest.TestCase):
    """V1GlobalContentFiltersGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GlobalContentFiltersGetResponse:
        """Test V1GlobalContentFiltersGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GlobalContentFiltersGetResponse`
        """
        model = V1GlobalContentFiltersGetResponse()
        if include_optional:
            return V1GlobalContentFiltersGetResponse(
                rows = [
                    graphiant_sdk.models.v1_global_content_filters_get_response_row.v1GlobalContentFiltersGetResponseRow(
                        created_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        global_content_filter_id = 1234567891011, 
                        global_content_filter_name = 'example string', 
                        lans = [
                            graphiant_sdk.models.v1_global_content_filters_get_response_row_lan_entry.v1GlobalContentFiltersGetResponseRowLanEntry(
                                lan_name = 'example string', )
                            ], 
                        rules = [
                            graphiant_sdk.models.v1_global_content_filters_get_response_row_rule_entry.v1GlobalContentFiltersGetResponseRowRuleEntry(
                                domain_category = 'example string', 
                                exception_wildcards = [
                                    'example string'
                                    ], )
                            ], 
                        sites = [
                            graphiant_sdk.models.v1_global_content_filters_get_response_row_site_entry.v1GlobalContentFiltersGetResponseRowSiteEntry(
                                site_name = 'example string', )
                            ], 
                        updated_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), )
                    ]
            )
        else:
            return V1GlobalContentFiltersGetResponse(
        )
        """

    def testV1GlobalContentFiltersGetResponse(self):
        """Test V1GlobalContentFiltersGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
