# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_ztagent_agents_get_response import V1ZtagentAgentsGetResponse

class TestV1ZtagentAgentsGetResponse(unittest.TestCase):
    """V1ZtagentAgentsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ZtagentAgentsGetResponse:
        """Test V1ZtagentAgentsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ZtagentAgentsGetResponse`
        """
        model = V1ZtagentAgentsGetResponse()
        if include_optional:
            return V1ZtagentAgentsGetResponse(
                agents = [
                    graphiant_sdk.models.conceal_agent.concealAgent(
                        created_at = 'example string', 
                        disabled = True, 
                        id = 'example string', 
                        identifier = 'example string', 
                        last_checkin = 'example string', 
                        machine = 'example string', )
                    ],
                count = 123
            )
        else:
            return V1ZtagentAgentsGetResponse(
        )
        """

    def testV1ZtagentAgentsGetResponse(self):
        """Test V1ZtagentAgentsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
