# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_software_rollouts_post_response import V1SoftwareRolloutsPostResponse

class TestV1SoftwareRolloutsPostResponse(unittest.TestCase):
    """V1SoftwareRolloutsPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SoftwareRolloutsPostResponse:
        """Test V1SoftwareRolloutsPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SoftwareRolloutsPostResponse`
        """
        model = V1SoftwareRolloutsPostResponse()
        if include_optional:
            return V1SoftwareRolloutsPostResponse(
                id = 42
            )
        else:
            return V1SoftwareRolloutsPostResponse(
        )
        """

    def testV1SoftwareRolloutsPostResponse(self):
        """Test V1SoftwareRolloutsPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
