# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_managed_enterprise_contract_info import ManaV2ManagedEnterpriseContractInfo

class TestManaV2ManagedEnterpriseContractInfo(unittest.TestCase):
    """ManaV2ManagedEnterpriseContractInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2ManagedEnterpriseContractInfo:
        """Test ManaV2ManagedEnterpriseContractInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2ManagedEnterpriseContractInfo`
        """
        model = ManaV2ManagedEnterpriseContractInfo()
        if include_optional:
            return ManaV2ManagedEnterpriseContractInfo(
                consumed_credits = 12.34,
                enterprise_contract = graphiant_sdk.models.common_billing_contract.commonBillingContract(
                    contracted_credits = 12.34, 
                    expiration_date = graphiant_sdk.models.common_billing_time_period.commonBillingTimePeriod(
                        month = 123, 
                        year = 123, ), ),
                enterprise_id = 1234567891011,
                enterprise_name = 'example string'
            )
        else:
            return ManaV2ManagedEnterpriseContractInfo(
        )
        """

    def testManaV2ManagedEnterpriseContractInfo(self):
        """Test ManaV2ManagedEnterpriseContractInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
