# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.upgrade_monthly_recurrence import UpgradeMonthlyRecurrence

class TestUpgradeMonthlyRecurrence(unittest.TestCase):
    """UpgradeMonthlyRecurrence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpgradeMonthlyRecurrence:
        """Test UpgradeMonthlyRecurrence
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpgradeMonthlyRecurrence`
        """
        model = UpgradeMonthlyRecurrence()
        if include_optional:
            return UpgradeMonthlyRecurrence(
                var_date = 15,
                ordinal = 'Second',
                weekday = 'Tuesday'
            )
        else:
            return UpgradeMonthlyRecurrence(
        )
        """

    def testUpgradeMonthlyRecurrence(self):
        """Test UpgradeMonthlyRecurrence"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
