# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_assurance_get_app_names_post_request import V2AssuranceGetAppNamesPostRequest

class TestV2AssuranceGetAppNamesPostRequest(unittest.TestCase):
    """V2AssuranceGetAppNamesPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2AssuranceGetAppNamesPostRequest:
        """Test V2AssuranceGetAppNamesPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2AssuranceGetAppNamesPostRequest`
        """
        model = V2AssuranceGetAppNamesPostRequest()
        if include_optional:
            return V2AssuranceGetAppNamesPostRequest(
                tags = [
                    'ENUM_VALUE'
                    ]
            )
        else:
            return V2AssuranceGetAppNamesPostRequest(
                tags = [
                    'ENUM_VALUE'
                    ],
        )
        """

    def testV2AssuranceGetAppNamesPostRequest(self):
        """Test V2AssuranceGetAppNamesPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
