# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_public_vif_consumer_policy import ManaV2PublicVifConsumerPolicy

class TestManaV2PublicVifConsumerPolicy(unittest.TestCase):
    """ManaV2PublicVifConsumerPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2PublicVifConsumerPolicy:
        """Test ManaV2PublicVifConsumerPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2PublicVifConsumerPolicy`
        """
        model = ManaV2PublicVifConsumerPolicy()
        if include_optional:
            return ManaV2PublicVifConsumerPolicy(
                lan_segments = [
                    graphiant_sdk.models.mana_v2_public_vif_consumer_lan_segment.manaV2PublicVifConsumerLanSegment(
                        allowed_prefixes = [
                            'example string'
                            ], 
                        service_lan_segment = 1234567891011, )
                    ],
                sites = graphiant_sdk.models.mana_v2_site_information.manaV2SiteInformation(
                    site_lists = [
                        1234567891011
                        ], )
            )
        else:
            return ManaV2PublicVifConsumerPolicy(
                lan_segments = [
                    graphiant_sdk.models.mana_v2_public_vif_consumer_lan_segment.manaV2PublicVifConsumerLanSegment(
                        allowed_prefixes = [
                            'example string'
                            ], 
                        service_lan_segment = 1234567891011, )
                    ],
                sites = graphiant_sdk.models.mana_v2_site_information.manaV2SiteInformation(
                    site_lists = [
                        1234567891011
                        ], ),
        )
        """

    def testManaV2PublicVifConsumerPolicy(self):
        """Test ManaV2PublicVifConsumerPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
