# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_monitoring_macsec_device_id_status_get_response_ma_csec_status import V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus

class TestV2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus(unittest.TestCase):
    """V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus:
        """Test V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus`
        """
        model = V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus()
        if include_optional:
            return V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus(
                interface_name = 'example string',
                status = 'ENUM_VALUE'
            )
        else:
            return V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus(
        )
        """

    def testV2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus(self):
        """Test V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
