# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_public_vif_consumer_lan_segment import ManaV2PublicVifConsumerLanSegment

class TestManaV2PublicVifConsumerLanSegment(unittest.TestCase):
    """ManaV2PublicVifConsumerLanSegment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2PublicVifConsumerLanSegment:
        """Test ManaV2PublicVifConsumerLanSegment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2PublicVifConsumerLanSegment`
        """
        model = ManaV2PublicVifConsumerLanSegment()
        if include_optional:
            return ManaV2PublicVifConsumerLanSegment(
                allowed_prefixes = [
                    'example string'
                    ],
                service_lan_segment = 1234567891011
            )
        else:
            return ManaV2PublicVifConsumerLanSegment(
                allowed_prefixes = [
                    'example string'
                    ],
                service_lan_segment = 1234567891011,
        )
        """

    def testManaV2PublicVifConsumerLanSegment(self):
        """Test ManaV2PublicVifConsumerLanSegment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
