# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_public_vif_producer_policy import ManaV2PublicVifProducerPolicy

class TestManaV2PublicVifProducerPolicy(unittest.TestCase):
    """ManaV2PublicVifProducerPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2PublicVifProducerPolicy:
        """Test ManaV2PublicVifProducerPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2PublicVifProducerPolicy`
        """
        model = ManaV2PublicVifProducerPolicy()
        if include_optional:
            return ManaV2PublicVifProducerPolicy(
                devices = {
                    'key' : graphiant_sdk.models.mana_v2_public_vif_device.manaV2PublicVifDevice(
                        consumer_burst_size = 123, 
                        consumer_bw_site = 123, 
                        nat_pools = [
                            'example string'
                            ], )
                    },
                profiles = [
                    graphiant_sdk.models.mana_v2_application_profile.manaV2ApplicationProfile(
                        port_range = 'example string', 
                        ports = [
                            123
                            ], 
                        protocol = 123, )
                    ],
                service_lan_segment = 1234567891011,
                service_name = 'example string',
                sites = graphiant_sdk.models.mana_v2_site_information.manaV2SiteInformation(
                    site_lists = [
                        1234567891011
                        ], ),
                sla = graphiant_sdk.models.mana_v2_sla_information.manaV2SlaInformation(
                    backup_circuit = 'ENUM_VALUE', 
                    class = 'ENUM_VALUE', 
                    primary_circuit = 'ENUM_VALUE', ),
                vifs = graphiant_sdk.models.mana_v2_public_vif.manaV2PublicVif(
                    covering_prefixes = graphiant_sdk.models.mana_v2_public_vif_dynamic.manaV2PublicVifDynamic(
                        entries = [
                            'example string'
                            ], ), 
                    fixed_prefixes = graphiant_sdk.models.mana_v2_public_vif_fixed.manaV2PublicVifFixed(), 
                    type = 'ENUM_VALUE', )
            )
        else:
            return ManaV2PublicVifProducerPolicy(
                devices = {
                    'key' : graphiant_sdk.models.mana_v2_public_vif_device.manaV2PublicVifDevice(
                        consumer_burst_size = 123, 
                        consumer_bw_site = 123, 
                        nat_pools = [
                            'example string'
                            ], )
                    },
                service_lan_segment = 1234567891011,
                sites = graphiant_sdk.models.mana_v2_site_information.manaV2SiteInformation(
                    site_lists = [
                        1234567891011
                        ], ),
                vifs = graphiant_sdk.models.mana_v2_public_vif.manaV2PublicVif(
                    covering_prefixes = graphiant_sdk.models.mana_v2_public_vif_dynamic.manaV2PublicVifDynamic(
                        entries = [
                            'example string'
                            ], ), 
                    fixed_prefixes = graphiant_sdk.models.mana_v2_public_vif_fixed.manaV2PublicVifFixed(), 
                    type = 'ENUM_VALUE', ),
        )
        """

    def testManaV2PublicVifProducerPolicy(self):
        """Test ManaV2PublicVifProducerPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
