# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_lan_segments_interfaces_public_get_response import V1LanSegmentsInterfacesPublicGetResponse

class TestV1LanSegmentsInterfacesPublicGetResponse(unittest.TestCase):
    """V1LanSegmentsInterfacesPublicGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1LanSegmentsInterfacesPublicGetResponse:
        """Test V1LanSegmentsInterfacesPublicGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1LanSegmentsInterfacesPublicGetResponse`
        """
        model = V1LanSegmentsInterfacesPublicGetResponse()
        if include_optional:
            return V1LanSegmentsInterfacesPublicGetResponse(
                lan_segment_ids = {
                    'key' : graphiant_sdk.models.mana_v2_lan_segment_public_interfaces_lists.manaV2LanSegmentPublicInterfacesLists(
                        private_interfaces = [
                            graphiant_sdk.models.mana_v2_lan_segment_public_interface_entry.manaV2LanSegmentPublicInterfaceEntry(
                                interface_id = 1234567891011, 
                                ipv4_addresses = [
                                    'example string'
                                    ], 
                                name = 'example string', 
                                storage_provider = 'ENUM_VALUE', )
                            ], 
                        public_interfaces = [
                            graphiant_sdk.models.mana_v2_lan_segment_public_interface_entry.manaV2LanSegmentPublicInterfaceEntry(
                                interface_id = 1234567891011, 
                                name = 'example string', 
                                storage_provider = 'ENUM_VALUE', )
                            ], )
                    }
            )
        else:
            return V1LanSegmentsInterfacesPublicGetResponse(
        )
        """

    def testV1LanSegmentsInterfacesPublicGetResponse(self):
        """Test V1LanSegmentsInterfacesPublicGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
