# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_global_content_filter_config import ManaV2GlobalContentFilterConfig

class TestManaV2GlobalContentFilterConfig(unittest.TestCase):
    """ManaV2GlobalContentFilterConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2GlobalContentFilterConfig:
        """Test ManaV2GlobalContentFilterConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2GlobalContentFilterConfig`
        """
        model = ManaV2GlobalContentFilterConfig()
        if include_optional:
            return ManaV2GlobalContentFilterConfig(
                lan_names = [
                    'example string'
                    ],
                name = 'example string',
                rules = [
                    graphiant_sdk.models.mana_v2_global_content_filter_rule.manaV2GlobalContentFilterRule(
                        domain_category_id = 1234567891011, 
                        exception_wildcards = [
                            'example string'
                            ], )
                    ],
                site_list_id = 1234567891011,
                use_all_sites = True
            )
        else:
            return ManaV2GlobalContentFilterConfig(
        )
        """

    def testManaV2GlobalContentFilterConfig(self):
        """Test ManaV2GlobalContentFilterConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
