# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_users_passwords_expire_post_response import V1UsersPasswordsExpirePostResponse

class TestV1UsersPasswordsExpirePostResponse(unittest.TestCase):
    """V1UsersPasswordsExpirePostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1UsersPasswordsExpirePostResponse:
        """Test V1UsersPasswordsExpirePostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1UsersPasswordsExpirePostResponse`
        """
        model = V1UsersPasswordsExpirePostResponse()
        if include_optional:
            return V1UsersPasswordsExpirePostResponse(
                failed_count = 123,
                failed_users = [
                    graphiant_sdk.models.iam_failed_user.iamFailedUser(
                        reason = 'example string', 
                        user_id = 'example string', )
                    ],
                success_count = 123
            )
        else:
            return V1UsersPasswordsExpirePostResponse(
        )
        """

    def testV1UsersPasswordsExpirePostResponse(self):
        """Test V1UsersPasswordsExpirePostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
