# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_global_content_filters_get_response_row_site_entry import V1GlobalContentFiltersGetResponseRowSiteEntry

class TestV1GlobalContentFiltersGetResponseRowSiteEntry(unittest.TestCase):
    """V1GlobalContentFiltersGetResponseRowSiteEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GlobalContentFiltersGetResponseRowSiteEntry:
        """Test V1GlobalContentFiltersGetResponseRowSiteEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GlobalContentFiltersGetResponseRowSiteEntry`
        """
        model = V1GlobalContentFiltersGetResponseRowSiteEntry()
        if include_optional:
            return V1GlobalContentFiltersGetResponseRowSiteEntry(
                site_name = 'example string'
            )
        else:
            return V1GlobalContentFiltersGetResponseRowSiteEntry(
        )
        """

    def testV1GlobalContentFiltersGetResponseRowSiteEntry(self):
        """Test V1GlobalContentFiltersGetResponseRowSiteEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
