# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_assurance_create_ai_adoption_approve_entry_post_request import V2AssuranceCreateAiAdoptionApproveEntryPostRequest

class TestV2AssuranceCreateAiAdoptionApproveEntryPostRequest(unittest.TestCase):
    """V2AssuranceCreateAiAdoptionApproveEntryPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2AssuranceCreateAiAdoptionApproveEntryPostRequest:
        """Test V2AssuranceCreateAiAdoptionApproveEntryPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2AssuranceCreateAiAdoptionApproveEntryPostRequest`
        """
        model = V2AssuranceCreateAiAdoptionApproveEntryPostRequest()
        if include_optional:
            return V2AssuranceCreateAiAdoptionApproveEntryPostRequest(
                approved_app_entry = graphiant_sdk.models.assurance_approved_app_entry_request.assuranceApprovedAppEntryRequest(
                    app_name = 'example string', 
                    domain = 'example string', 
                    id = 'example string', 
                    tag_requested = 'ENUM_VALUE', )
            )
        else:
            return V2AssuranceCreateAiAdoptionApproveEntryPostRequest(
                approved_app_entry = graphiant_sdk.models.assurance_approved_app_entry_request.assuranceApprovedAppEntryRequest(
                    app_name = 'example string', 
                    domain = 'example string', 
                    id = 'example string', 
                    tag_requested = 'ENUM_VALUE', ),
        )
        """

    def testV2AssuranceCreateAiAdoptionApproveEntryPostRequest(self):
        """Test V2AssuranceCreateAiAdoptionApproveEntryPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
