# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.assurance_what_widget import AssuranceWhatWidget

class TestAssuranceWhatWidget(unittest.TestCase):
    """AssuranceWhatWidget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssuranceWhatWidget:
        """Test AssuranceWhatWidget
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssuranceWhatWidget`
        """
        model = AssuranceWhatWidget()
        if include_optional:
            return AssuranceWhatWidget(
                bubble_categories = [
                    graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                        delta = 123.45, 
                        name = 'example string', 
                        percent = 123.45, 
                        tag = 'ENUM_VALUE', 
                        value = 123.45, )
                    ],
                top_tools_by_active_users = [
                    graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                        delta = 123.45, 
                        name = 'example string', 
                        percent = 123.45, 
                        tag = 'ENUM_VALUE', 
                        value = 123.45, )
                    ],
                top_tools_by_data_transferred = [
                    graphiant_sdk.models.assurance_kpi_metric.assuranceKpiMetric(
                        delta = 123.45, 
                        name = 'example string', 
                        percent = 123.45, 
                        tag = 'ENUM_VALUE', 
                        value = 123.45, )
                    ]
            )
        else:
            return AssuranceWhatWidget(
        )
        """

    def testAssuranceWhatWidget(self):
        """Test AssuranceWhatWidget"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
