# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.alertservice_integration_details import AlertserviceIntegrationDetails
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AlertserviceCreateIntegrationBody(BaseModel):
    """
    AlertserviceCreateIntegrationBody
    """ # noqa: E501
    created_by: Optional[StrictStr] = Field(default=None, description="ID of the user who created the integration", alias="createdBy", json_schema_extra={"examples": ["example string"]})
    created_on: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="createdOn")
    details: Optional[AlertserviceIntegrationDetails] = None
    enterprise: StrictInt = Field(description="ID of the enterprise (required)", json_schema_extra={"examples": [1234567891011]})
    integration_type: StrictStr = Field(description="Type of integration (required)", alias="integrationType", json_schema_extra={"examples": ["ENUM_VALUE"]})
    is_active: Optional[StrictBool] = Field(default=None, description="Indicates whether the integration is active", alias="isActive", json_schema_extra={"examples": [True]})
    nick_name: StrictStr = Field(description="Name of the integration (required)", alias="nickName", json_schema_extra={"examples": ["example string"]})
    __properties: ClassVar[List[str]] = ["createdBy", "createdOn", "details", "enterprise", "integrationType", "isActive", "nickName"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AlertserviceCreateIntegrationBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_on
        if self.created_on:
            _dict['createdOn'] = self.created_on.to_dict()
        # override the default output from pydantic by calling `to_dict()` of details
        if self.details:
            _dict['details'] = self.details.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AlertserviceCreateIntegrationBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdBy": obj.get("createdBy"),
            "createdOn": GoogleProtobufTimestamp.from_dict(obj["createdOn"]) if obj.get("createdOn") is not None else None,
            "details": AlertserviceIntegrationDetails.from_dict(obj["details"]) if obj.get("details") is not None else None,
            "enterprise": obj.get("enterprise"),
            "integrationType": obj.get("integrationType"),
            "isActive": obj.get("isActive"),
            "nickName": obj.get("nickName")
        })
        return _obj


