# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AssuranceEnterpriseSummary(BaseModel):
    """
    AssuranceEnterpriseSummary
    """ # noqa: E501
    flows_analyzed: Optional[StrictInt] = Field(default=None, alias="flowsAnalyzed", json_schema_extra={"examples": [1234567891011]})
    gap_score: Optional[StrictInt] = Field(default=None, alias="gapScore", json_schema_extra={"examples": [1234567891011]})
    prev_gap_score: Optional[StrictInt] = Field(default=None, alias="prevGapScore", json_schema_extra={"examples": [1234567891011]})
    risk_bin: Optional[StrictInt] = Field(default=None, alias="riskBin", json_schema_extra={"examples": [1234567891011]})
    threat_count: Optional[StrictInt] = Field(default=None, alias="threatCount", json_schema_extra={"examples": [1234567891011]})
    unique_apps_count: Optional[StrictInt] = Field(default=None, alias="uniqueAppsCount", json_schema_extra={"examples": [1234567891011]})
    __properties: ClassVar[List[str]] = ["flowsAnalyzed", "gapScore", "prevGapScore", "riskBin", "threatCount", "uniqueAppsCount"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssuranceEnterpriseSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssuranceEnterpriseSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "flowsAnalyzed": obj.get("flowsAnalyzed"),
            "gapScore": obj.get("gapScore"),
            "prevGapScore": obj.get("prevGapScore"),
            "riskBin": obj.get("riskBin"),
            "threatCount": obj.get("threatCount"),
            "uniqueAppsCount": obj.get("uniqueAppsCount")
        })
        return _obj


