# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.assurance_kpi_metric import AssuranceKpiMetric
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AssuranceWhenWidget(BaseModel):
    """
    AssuranceWhenWidget
    """ # noqa: E501
    day_of_week: Optional[List[AssuranceKpiMetric]] = Field(default=None, alias="dayOfWeek")
    hour_of_day: Optional[List[AssuranceKpiMetric]] = Field(default=None, alias="hourOfDay")
    monthly_active_users: Optional[List[AssuranceKpiMetric]] = Field(default=None, alias="monthlyActiveUsers")
    monthly_bandwidth_transferred: Optional[List[AssuranceKpiMetric]] = Field(default=None, alias="monthlyBandwidthTransferred")
    __properties: ClassVar[List[str]] = ["dayOfWeek", "hourOfDay", "monthlyActiveUsers", "monthlyBandwidthTransferred"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssuranceWhenWidget from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in day_of_week (list)
        _items = []
        if self.day_of_week:
            for _item_day_of_week in self.day_of_week:
                if _item_day_of_week:
                    _items.append(_item_day_of_week.to_dict())
            _dict['dayOfWeek'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in hour_of_day (list)
        _items = []
        if self.hour_of_day:
            for _item_hour_of_day in self.hour_of_day:
                if _item_hour_of_day:
                    _items.append(_item_hour_of_day.to_dict())
            _dict['hourOfDay'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in monthly_active_users (list)
        _items = []
        if self.monthly_active_users:
            for _item_monthly_active_users in self.monthly_active_users:
                if _item_monthly_active_users:
                    _items.append(_item_monthly_active_users.to_dict())
            _dict['monthlyActiveUsers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in monthly_bandwidth_transferred (list)
        _items = []
        if self.monthly_bandwidth_transferred:
            for _item_monthly_bandwidth_transferred in self.monthly_bandwidth_transferred:
                if _item_monthly_bandwidth_transferred:
                    _items.append(_item_monthly_bandwidth_transferred.to_dict())
            _dict['monthlyBandwidthTransferred'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssuranceWhenWidget from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dayOfWeek": [AssuranceKpiMetric.from_dict(_item) for _item in obj["dayOfWeek"]] if obj.get("dayOfWeek") is not None else None,
            "hourOfDay": [AssuranceKpiMetric.from_dict(_item) for _item in obj["hourOfDay"]] if obj.get("hourOfDay") is not None else None,
            "monthlyActiveUsers": [AssuranceKpiMetric.from_dict(_item) for _item in obj["monthlyActiveUsers"]] if obj.get("monthlyActiveUsers") is not None else None,
            "monthlyBandwidthTransferred": [AssuranceKpiMetric.from_dict(_item) for _item in obj["monthlyBandwidthTransferred"]] if obj.get("monthlyBandwidthTransferred") is not None else None
        })
        return _obj


