# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.assurance_kpi_metric import AssuranceKpiMetric
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AssuranceTopLevelKpi(BaseModel):
    """
    AssuranceTopLevelKpi
    """ # noqa: E501
    data_transferred_kbps_metric: Optional[AssuranceKpiMetric] = Field(default=None, alias="dataTransferredKbpsMetric")
    shadow_ai_tools_metric: Optional[AssuranceKpiMetric] = Field(default=None, alias="shadowAiToolsMetric")
    tools_metric: Optional[AssuranceKpiMetric] = Field(default=None, alias="toolsMetric")
    users_metric: Optional[AssuranceKpiMetric] = Field(default=None, alias="usersMetric")
    __properties: ClassVar[List[str]] = ["dataTransferredKbpsMetric", "shadowAiToolsMetric", "toolsMetric", "usersMetric"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssuranceTopLevelKpi from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data_transferred_kbps_metric
        if self.data_transferred_kbps_metric:
            _dict['dataTransferredKbpsMetric'] = self.data_transferred_kbps_metric.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shadow_ai_tools_metric
        if self.shadow_ai_tools_metric:
            _dict['shadowAiToolsMetric'] = self.shadow_ai_tools_metric.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tools_metric
        if self.tools_metric:
            _dict['toolsMetric'] = self.tools_metric.to_dict()
        # override the default output from pydantic by calling `to_dict()` of users_metric
        if self.users_metric:
            _dict['usersMetric'] = self.users_metric.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssuranceTopLevelKpi from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dataTransferredKbpsMetric": AssuranceKpiMetric.from_dict(obj["dataTransferredKbpsMetric"]) if obj.get("dataTransferredKbpsMetric") is not None else None,
            "shadowAiToolsMetric": AssuranceKpiMetric.from_dict(obj["shadowAiToolsMetric"]) if obj.get("shadowAiToolsMetric") is not None else None,
            "toolsMetric": AssuranceKpiMetric.from_dict(obj["toolsMetric"]) if obj.get("toolsMetric") is not None else None,
            "usersMetric": AssuranceKpiMetric.from_dict(obj["usersMetric"]) if obj.get("usersMetric") is not None else None
        })
        return _obj


