# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CommonUser(BaseModel):
    """
    CommonUser
    """ # noqa: E501
    email: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    enterprise_id: Optional[StrictInt] = Field(default=None, alias="enterpriseId", json_schema_extra={"examples": [1234567891011]})
    first_name: Optional[StrictStr] = Field(default=None, alias="firstName", json_schema_extra={"examples": ["example string"]})
    last_active_at: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="lastActiveAt")
    last_name: Optional[StrictStr] = Field(default=None, alias="lastName", json_schema_extra={"examples": ["example string"]})
    mfa_factor: Optional[StrictStr] = Field(default=None, alias="mfaFactor", json_schema_extra={"examples": ["example string"]})
    phone_number: Optional[StrictStr] = Field(default=None, alias="phoneNumber", json_schema_extra={"examples": ["example string"]})
    time_zone: Optional[StrictStr] = Field(default=None, alias="timeZone", json_schema_extra={"examples": ["example string"]})
    user_id: Optional[StrictStr] = Field(default=None, alias="userId", json_schema_extra={"examples": ["example string"]})
    verified: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    __properties: ClassVar[List[str]] = ["email", "enterpriseId", "firstName", "lastActiveAt", "lastName", "mfaFactor", "phoneNumber", "timeZone", "userId", "verified"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CommonUser from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of last_active_at
        if self.last_active_at:
            _dict['lastActiveAt'] = self.last_active_at.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CommonUser from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "email": obj.get("email"),
            "enterpriseId": obj.get("enterpriseId"),
            "firstName": obj.get("firstName"),
            "lastActiveAt": GoogleProtobufTimestamp.from_dict(obj["lastActiveAt"]) if obj.get("lastActiveAt") is not None else None,
            "lastName": obj.get("lastName"),
            "mfaFactor": obj.get("mfaFactor"),
            "phoneNumber": obj.get("phoneNumber"),
            "timeZone": obj.get("timeZone"),
            "userId": obj.get("userId"),
            "verified": obj.get("verified")
        })
        return _obj


