# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2BgpDynamicNeighborOperPeer(BaseModel):
    """
    ManaV2BgpDynamicNeighborOperPeer
    """ # noqa: E501
    last_oper_status_change: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="lastOperStatusChange")
    local_address: Optional[StrictStr] = Field(default=None, description="Local address used for this peer session, if known from oper", alias="localAddress")
    oper_status: Optional[StrictBool] = Field(default=None, description="True when the BGP session to this peer is operationally up (e.g. established)", alias="operStatus")
    peer_asn: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Peer ASN from oper, if reported", alias="peerAsn")
    remote_address: Optional[StrictStr] = Field(default=None, description="Peer address from device oper state (IPv4/IPv6; may include IPv6 zone id)", alias="remoteAddress")
    state: Optional[StrictStr] = Field(default=None, description="BGP FSM state for this peer session")
    __properties: ClassVar[List[str]] = ["lastOperStatusChange", "localAddress", "operStatus", "peerAsn", "remoteAddress", "state"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2BgpDynamicNeighborOperPeer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of last_oper_status_change
        if self.last_oper_status_change:
            _dict['lastOperStatusChange'] = self.last_oper_status_change.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2BgpDynamicNeighborOperPeer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lastOperStatusChange": GoogleProtobufTimestamp.from_dict(obj["lastOperStatusChange"]) if obj.get("lastOperStatusChange") is not None else None,
            "localAddress": obj.get("localAddress"),
            "operStatus": obj.get("operStatus"),
            "peerAsn": obj.get("peerAsn"),
            "remoteAddress": obj.get("remoteAddress"),
            "state": obj.get("state")
        })
        return _obj


