# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.mana_v2_global_content_filter_rule import ManaV2GlobalContentFilterRule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2GlobalContentFilterConfig(BaseModel):
    """
    ManaV2GlobalContentFilterConfig
    """ # noqa: E501
    lan_names: Optional[List[StrictStr]] = Field(default=None, alias="lanNames")
    name: Optional[StrictStr] = Field(default=None, description="Display name for this global content filter configuration.")
    rules: Optional[List[ManaV2GlobalContentFilterRule]] = None
    site_list_id: Optional[StrictInt] = Field(default=None, description="Site list whose members this content filter applies to; omit the oneof when no site scope is set.", alias="siteListId")
    use_all_sites: Optional[StrictBool] = Field(default=None, description="When true, the filter applies to all sites in the tenant (must be the constant true).", alias="useAllSites")
    __properties: ClassVar[List[str]] = ["lanNames", "name", "rules", "siteListId", "useAllSites"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2GlobalContentFilterConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rules (list)
        _items = []
        if self.rules:
            for _item_rules in self.rules:
                if _item_rules:
                    _items.append(_item_rules.to_dict())
            _dict['rules'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2GlobalContentFilterConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lanNames": obj.get("lanNames"),
            "name": obj.get("name"),
            "rules": [ManaV2GlobalContentFilterRule.from_dict(_item) for _item in obj["rules"]] if obj.get("rules") is not None else None,
            "siteListId": obj.get("siteListId"),
            "useAllSites": obj.get("useAllSites")
        })
        return _obj


