# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2PskConfiguration(BaseModel):
    """
    ManaV2PskConfiguration
    """ # noqa: E501
    cak: Optional[StrictStr] = Field(default=None, description="The Connection Authentication Key (CAK)", json_schema_extra={"examples": ["1234567890abcdef1234567890abcdef"]})
    cak_cryptographic_algorithm: Optional[StrictStr] = Field(default=None, description="The cryptographic algorithm for the CAK, SAK Cipher Suite is implicitly selected based on this field. (required)", alias="cakCryptographicAlgorithm", json_schema_extra={"examples": ["AES_128_CMAC"]})
    ckn: Optional[StrictStr] = Field(default=None, description="The Connection Key Name (CKN) (required)", json_schema_extra={"examples": ["Corp-MACsec-CKN"]})
    nickname: Optional[StrictStr] = Field(default=None, description="The nickname of the PSK (required)", json_schema_extra={"examples": ["PSK1"]})
    start_time: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="startTime")
    use_xpn_for_cipher_suite: Optional[StrictBool] = Field(default=None, description="Whether to use XPN for the cipher suite. If true, AES_128_GCM_XPN or AES_256_GCM_XPN is selected based on the cmac algorithm. If false, AES_128_GCM or AES_256_GCM is selected based on the cmac algorithm.", alias="useXpnForCipherSuite", json_schema_extra={"examples": [True]})
    __properties: ClassVar[List[str]] = ["cak", "cakCryptographicAlgorithm", "ckn", "nickname", "startTime", "useXpnForCipherSuite"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2PskConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of start_time
        if self.start_time:
            _dict['startTime'] = self.start_time.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2PskConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cak": obj.get("cak"),
            "cakCryptographicAlgorithm": obj.get("cakCryptographicAlgorithm"),
            "ckn": obj.get("ckn"),
            "nickname": obj.get("nickname"),
            "startTime": GoogleProtobufTimestamp.from_dict(obj["startTime"]) if obj.get("startTime") is not None else None,
            "useXpnForCipherSuite": obj.get("useXpnForCipherSuite")
        })
        return _obj


