# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from graphiant_sdk.models.mana_v2_nullable_interface_priority_decrement import ManaV2NullableInterfacePriorityDecrement
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2VrrpGroupConfig(BaseModel):
    """
    ManaV2VrrpGroupConfig
    """ # noqa: E501
    accept_mode: Optional[StrictBool] = Field(default=None, alias="acceptMode", json_schema_extra={"examples": [True]})
    allow_inter_operability: Optional[StrictBool] = Field(default=None, alias="allowInterOperability", json_schema_extra={"examples": [True]})
    description: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    enabled: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    preempt: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    priority: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, json_schema_extra={"examples": [123]})
    tracked_interfaces: Optional[List[ManaV2NullableInterfacePriorityDecrement]] = Field(default=None, alias="trackedInterfaces")
    virtual_ip: Optional[StrictStr] = Field(default=None, alias="virtualIp", json_schema_extra={"examples": ["example string"]})
    virtual_router_id: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="virtualRouterId", json_schema_extra={"examples": [123]})
    __properties: ClassVar[List[str]] = ["acceptMode", "allowInterOperability", "description", "enabled", "preempt", "priority", "trackedInterfaces", "virtualIp", "virtualRouterId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2VrrpGroupConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tracked_interfaces (list)
        _items = []
        if self.tracked_interfaces:
            for _item_tracked_interfaces in self.tracked_interfaces:
                if _item_tracked_interfaces:
                    _items.append(_item_tracked_interfaces.to_dict())
            _dict['trackedInterfaces'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2VrrpGroupConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "acceptMode": obj.get("acceptMode"),
            "allowInterOperability": obj.get("allowInterOperability"),
            "description": obj.get("description"),
            "enabled": obj.get("enabled"),
            "preempt": obj.get("preempt"),
            "priority": obj.get("priority"),
            "trackedInterfaces": [ManaV2NullableInterfacePriorityDecrement.from_dict(_item) for _item in obj["trackedInterfaces"]] if obj.get("trackedInterfaces") is not None else None,
            "virtualIp": obj.get("virtualIp"),
            "virtualRouterId": obj.get("virtualRouterId")
        })
        return _obj


