# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from graphiant_sdk.models.mana_v2_forwarding_policy_match_config import ManaV2ForwardingPolicyMatchConfig
from graphiant_sdk.models.mana_v2_traffic_policy_ruleset_config_nullable_rule_rule_action import ManaV2TrafficPolicyRulesetConfigNullableRuleRuleAction
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2TrafficPolicyRulesetConfigNullableRuleRule(BaseModel):
    """
    ManaV2TrafficPolicyRulesetConfigNullableRuleRule
    """ # noqa: E501
    action: Optional[ManaV2TrafficPolicyRulesetConfigNullableRuleRuleAction] = None
    description: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    match: Optional[ManaV2ForwardingPolicyMatchConfig] = None
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    seq: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, json_schema_extra={"examples": [123]})
    __properties: ClassVar[List[str]] = ["action", "description", "match", "name", "seq"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2TrafficPolicyRulesetConfigNullableRuleRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of action
        if self.action:
            _dict['action'] = self.action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of match
        if self.match:
            _dict['match'] = self.match.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2TrafficPolicyRulesetConfigNullableRuleRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": ManaV2TrafficPolicyRulesetConfigNullableRuleRuleAction.from_dict(obj["action"]) if obj.get("action") is not None else None,
            "description": obj.get("description"),
            "match": ManaV2ForwardingPolicyMatchConfig.from_dict(obj["match"]) if obj.get("match") is not None else None,
            "name": obj.get("name"),
            "seq": obj.get("seq")
        })
        return _obj


