# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from graphiant_sdk.models.google_protobuf_duration import GoogleProtobufDuration
from graphiant_sdk.models.mana_v2_bfd_instance import ManaV2BfdInstance
from graphiant_sdk.models.mana_v2_bfd_neighbor import ManaV2BfdNeighbor
from graphiant_sdk.models.mana_v2_bgp_dynamic_neighbor_oper_peer import ManaV2BgpDynamicNeighborOperPeer
from graphiant_sdk.models.mana_v2_bgp_neighbor_address_family import ManaV2BgpNeighborAddressFamily
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2BgpNeighbor(BaseModel):
    """
    ManaV2BgpNeighbor
    """ # noqa: E501
    address_families: Optional[List[ManaV2BgpNeighborAddressFamily]] = Field(default=None, alias="addressFamilies")
    allow_as_in: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="allowAsIn", json_schema_extra={"examples": [123]})
    as_override: Optional[StrictBool] = Field(default=None, alias="asOverride", json_schema_extra={"examples": [True]})
    bfd: Optional[ManaV2BfdInstance] = None
    bfd_neighbor: Optional[ManaV2BfdNeighbor] = Field(default=None, alias="bfdNeighbor")
    bgp_type: Optional[StrictStr] = Field(default=None, alias="bgpType", json_schema_extra={"examples": ["ENUM_VALUE"]})
    default_originate: Optional[StrictStr] = Field(default=None, description="Set when default route needs to be advertised in BGP domain", alias="defaultOriginate", json_schema_extra={"examples": ["ENUM_VALUE"]})
    dynamic_neighbor_peers: Optional[List[ManaV2BgpDynamicNeighborOperPeer]] = Field(default=None, alias="dynamicNeighborPeers")
    enabled: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    hold_timer: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="holdTimer", json_schema_extra={"examples": [123]})
    id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1234567891011]})
    keepalive_timer: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="keepaliveTimer", json_schema_extra={"examples": [123]})
    local_address: Optional[StrictStr] = Field(default=None, alias="localAddress", json_schema_extra={"examples": ["example string"]})
    local_interface: Optional[StrictStr] = Field(default=None, alias="localInterface", json_schema_extra={"examples": ["example string"]})
    max_prefix: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Maximum number of prefixes that can be received from neighbor", alias="maxPrefix", json_schema_extra={"examples": [10000]})
    md5_password: Optional[StrictStr] = Field(default=None, alias="md5Password", json_schema_extra={"examples": ["example string"]})
    multi_hop: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Set when EBGP multi-hop functionality is enabled", alias="multiHop", json_schema_extra={"examples": [5]})
    peer_asn: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="peerAsn", json_schema_extra={"examples": [123]})
    remote_address: Optional[StrictStr] = Field(default=None, alias="remoteAddress", json_schema_extra={"examples": ["example string"]})
    remove_private_as: Optional[StrictBool] = Field(default=None, alias="removePrivateAs", json_schema_extra={"examples": [True]})
    send_community: Optional[StrictBool] = Field(default=None, description="Flag for sending standard, extended, and large communities", alias="sendCommunity", json_schema_extra={"examples": [True]})
    state: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ENUM_VALUE"]})
    time_since_last_oper_change: Optional[GoogleProtobufDuration] = Field(default=None, alias="timeSinceLastOperChange")
    up: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    __properties: ClassVar[List[str]] = ["addressFamilies", "allowAsIn", "asOverride", "bfd", "bfdNeighbor", "bgpType", "defaultOriginate", "dynamicNeighborPeers", "enabled", "holdTimer", "id", "keepaliveTimer", "localAddress", "localInterface", "maxPrefix", "md5Password", "multiHop", "peerAsn", "remoteAddress", "removePrivateAs", "sendCommunity", "state", "timeSinceLastOperChange", "up"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2BgpNeighbor from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in address_families (list)
        _items = []
        if self.address_families:
            for _item_address_families in self.address_families:
                if _item_address_families:
                    _items.append(_item_address_families.to_dict())
            _dict['addressFamilies'] = _items
        # override the default output from pydantic by calling `to_dict()` of bfd
        if self.bfd:
            _dict['bfd'] = self.bfd.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bfd_neighbor
        if self.bfd_neighbor:
            _dict['bfdNeighbor'] = self.bfd_neighbor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in dynamic_neighbor_peers (list)
        _items = []
        if self.dynamic_neighbor_peers:
            for _item_dynamic_neighbor_peers in self.dynamic_neighbor_peers:
                if _item_dynamic_neighbor_peers:
                    _items.append(_item_dynamic_neighbor_peers.to_dict())
            _dict['dynamicNeighborPeers'] = _items
        # override the default output from pydantic by calling `to_dict()` of time_since_last_oper_change
        if self.time_since_last_oper_change:
            _dict['timeSinceLastOperChange'] = self.time_since_last_oper_change.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2BgpNeighbor from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addressFamilies": [ManaV2BgpNeighborAddressFamily.from_dict(_item) for _item in obj["addressFamilies"]] if obj.get("addressFamilies") is not None else None,
            "allowAsIn": obj.get("allowAsIn"),
            "asOverride": obj.get("asOverride"),
            "bfd": ManaV2BfdInstance.from_dict(obj["bfd"]) if obj.get("bfd") is not None else None,
            "bfdNeighbor": ManaV2BfdNeighbor.from_dict(obj["bfdNeighbor"]) if obj.get("bfdNeighbor") is not None else None,
            "bgpType": obj.get("bgpType"),
            "defaultOriginate": obj.get("defaultOriginate"),
            "dynamicNeighborPeers": [ManaV2BgpDynamicNeighborOperPeer.from_dict(_item) for _item in obj["dynamicNeighborPeers"]] if obj.get("dynamicNeighborPeers") is not None else None,
            "enabled": obj.get("enabled"),
            "holdTimer": obj.get("holdTimer"),
            "id": obj.get("id"),
            "keepaliveTimer": obj.get("keepaliveTimer"),
            "localAddress": obj.get("localAddress"),
            "localInterface": obj.get("localInterface"),
            "maxPrefix": obj.get("maxPrefix"),
            "md5Password": obj.get("md5Password"),
            "multiHop": obj.get("multiHop"),
            "peerAsn": obj.get("peerAsn"),
            "remoteAddress": obj.get("remoteAddress"),
            "removePrivateAs": obj.get("removePrivateAs"),
            "sendCommunity": obj.get("sendCommunity"),
            "state": obj.get("state"),
            "timeSinceLastOperChange": GoogleProtobufDuration.from_dict(obj["timeSinceLastOperChange"]) if obj.get("timeSinceLastOperChange") is not None else None,
            "up": obj.get("up")
        })
        return _obj


