# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from graphiant_sdk.models.google_protobuf_duration import GoogleProtobufDuration
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2topologyDevice(BaseModel):
    """
    ManaV2topologyDevice
    """ # noqa: E501
    device_id: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="deviceId", json_schema_extra={"examples": [12345678910]})
    hostname: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    location: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    maintenance_mode: Optional[StrictBool] = Field(default=None, alias="maintenanceMode", json_schema_extra={"examples": [True]})
    management_ip: Optional[StrictStr] = Field(default=None, alias="managementIp", json_schema_extra={"examples": ["example string"]})
    model: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    role: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ENUM_VALUE"]})
    serial_number: Optional[StrictStr] = Field(default=None, alias="serialNumber", json_schema_extra={"examples": ["example string"]})
    site_id: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="siteId", json_schema_extra={"examples": [12345678910]})
    software_version: Optional[StrictStr] = Field(default=None, alias="softwareVersion", json_schema_extra={"examples": ["example string"]})
    staging_mode: Optional[StrictBool] = Field(default=None, alias="stagingMode", json_schema_extra={"examples": [True]})
    uptime: Optional[GoogleProtobufDuration] = None
    vrrp_interface: Optional[StrictStr] = Field(default=None, alias="vrrpInterface", json_schema_extra={"examples": ["example string"]})
    vrrp_state: Optional[StrictStr] = Field(default=None, alias="vrrpState", json_schema_extra={"examples": ["ENUM_VALUE"]})
    __properties: ClassVar[List[str]] = ["deviceId", "hostname", "location", "maintenanceMode", "managementIp", "model", "role", "serialNumber", "siteId", "softwareVersion", "stagingMode", "uptime", "vrrpInterface", "vrrpState"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2topologyDevice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of uptime
        if self.uptime:
            _dict['uptime'] = self.uptime.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2topologyDevice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "deviceId": obj.get("deviceId"),
            "hostname": obj.get("hostname"),
            "location": obj.get("location"),
            "maintenanceMode": obj.get("maintenanceMode"),
            "managementIp": obj.get("managementIp"),
            "model": obj.get("model"),
            "role": obj.get("role"),
            "serialNumber": obj.get("serialNumber"),
            "siteId": obj.get("siteId"),
            "softwareVersion": obj.get("softwareVersion"),
            "stagingMode": obj.get("stagingMode"),
            "uptime": GoogleProtobufDuration.from_dict(obj["uptime"]) if obj.get("uptime") is not None else None,
            "vrrpInterface": obj.get("vrrpInterface"),
            "vrrpState": obj.get("vrrpState")
        })
        return _obj


