# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.mana_v2_application_profile import ManaV2ApplicationProfile
from graphiant_sdk.models.mana_v2_public_vif import ManaV2PublicVif
from graphiant_sdk.models.mana_v2_public_vif_device import ManaV2PublicVifDevice
from graphiant_sdk.models.mana_v2_security_policy_rule import ManaV2SecurityPolicyRule
from graphiant_sdk.models.mana_v2_site_information import ManaV2SiteInformation
from graphiant_sdk.models.mana_v2_sla_information import ManaV2SlaInformation
from graphiant_sdk.models.mana_v2_traffic_policy_rule import ManaV2TrafficPolicyRule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2PublicVifProducerPolicyResponse(BaseModel):
    """
    ManaV2PublicVifProducerPolicyResponse
    """ # noqa: E501
    devices: Optional[Dict[str, ManaV2PublicVifDevice]] = None
    inbound_security_rules: Optional[List[ManaV2SecurityPolicyRule]] = Field(default=None, alias="inboundSecurityRules")
    profiles: Optional[List[ManaV2ApplicationProfile]] = None
    service_lan_segment: Optional[StrictInt] = Field(default=None, description="LAN segment ID for the service", alias="serviceLanSegment", json_schema_extra={"examples": [1234567891011]})
    service_name: Optional[StrictStr] = Field(default=None, description="Public VIF service name (local_extranet_producer_service.name)", alias="serviceName", json_schema_extra={"examples": ["example string"]})
    sites: Optional[ManaV2SiteInformation] = None
    sla: Optional[ManaV2SlaInformation] = None
    traffic_rules: Optional[List[ManaV2TrafficPolicyRule]] = Field(default=None, alias="trafficRules")
    vifs: Optional[ManaV2PublicVif] = None
    __properties: ClassVar[List[str]] = ["devices", "inboundSecurityRules", "profiles", "serviceLanSegment", "serviceName", "sites", "sla", "trafficRules", "vifs"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2PublicVifProducerPolicyResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in devices (dict)
        _field_dict = {}
        if self.devices:
            for _key_devices in self.devices:
                if self.devices[_key_devices]:
                    _field_dict[_key_devices] = self.devices[_key_devices].to_dict()
            _dict['devices'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in inbound_security_rules (list)
        _items = []
        if self.inbound_security_rules:
            for _item_inbound_security_rules in self.inbound_security_rules:
                if _item_inbound_security_rules:
                    _items.append(_item_inbound_security_rules.to_dict())
            _dict['inboundSecurityRules'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in profiles (list)
        _items = []
        if self.profiles:
            for _item_profiles in self.profiles:
                if _item_profiles:
                    _items.append(_item_profiles.to_dict())
            _dict['profiles'] = _items
        # override the default output from pydantic by calling `to_dict()` of sites
        if self.sites:
            _dict['sites'] = self.sites.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sla
        if self.sla:
            _dict['sla'] = self.sla.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in traffic_rules (list)
        _items = []
        if self.traffic_rules:
            for _item_traffic_rules in self.traffic_rules:
                if _item_traffic_rules:
                    _items.append(_item_traffic_rules.to_dict())
            _dict['trafficRules'] = _items
        # override the default output from pydantic by calling `to_dict()` of vifs
        if self.vifs:
            _dict['vifs'] = self.vifs.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2PublicVifProducerPolicyResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "devices": dict(
                (_k, ManaV2PublicVifDevice.from_dict(_v))
                for _k, _v in obj["devices"].items()
            )
            if obj.get("devices") is not None
            else None,
            "inboundSecurityRules": [ManaV2SecurityPolicyRule.from_dict(_item) for _item in obj["inboundSecurityRules"]] if obj.get("inboundSecurityRules") is not None else None,
            "profiles": [ManaV2ApplicationProfile.from_dict(_item) for _item in obj["profiles"]] if obj.get("profiles") is not None else None,
            "serviceLanSegment": obj.get("serviceLanSegment"),
            "serviceName": obj.get("serviceName"),
            "sites": ManaV2SiteInformation.from_dict(obj["sites"]) if obj.get("sites") is not None else None,
            "sla": ManaV2SlaInformation.from_dict(obj["sla"]) if obj.get("sla") is not None else None,
            "trafficRules": [ManaV2TrafficPolicyRule.from_dict(_item) for _item in obj["trafficRules"]] if obj.get("trafficRules") is not None else None,
            "vifs": ManaV2PublicVif.from_dict(obj["vifs"]) if obj.get("vifs") is not None else None
        })
        return _obj


