# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.mana_v2_dscp import ManaV2Dscp
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2TrafficPolicyRulesetRuleAction(BaseModel):
    """
    ManaV2TrafficPolicyRulesetRuleAction
    """ # noqa: E501
    backup_circuit: Optional[StrictStr] = Field(default=None, alias="backupCircuit", json_schema_extra={"examples": ["example string"]})
    backup_circuit_label: Optional[StrictStr] = Field(default=None, alias="backupCircuitLabel", json_schema_extra={"examples": ["example string"]})
    egress: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ENUM_VALUE"]})
    logging: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    primary_circuit: Optional[StrictStr] = Field(default=None, alias="primaryCircuit", json_schema_extra={"examples": ["example string"]})
    primary_circuit_label: Optional[StrictStr] = Field(default=None, alias="primaryCircuitLabel", json_schema_extra={"examples": ["example string"]})
    remark: Optional[ManaV2Dscp] = None
    sla_class: Optional[StrictStr] = Field(default=None, alias="slaClass", json_schema_extra={"examples": ["ENUM_VALUE"]})
    __properties: ClassVar[List[str]] = ["backupCircuit", "backupCircuitLabel", "egress", "logging", "primaryCircuit", "primaryCircuitLabel", "remark", "slaClass"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2TrafficPolicyRulesetRuleAction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of remark
        if self.remark:
            _dict['remark'] = self.remark.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2TrafficPolicyRulesetRuleAction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "backupCircuit": obj.get("backupCircuit"),
            "backupCircuitLabel": obj.get("backupCircuitLabel"),
            "egress": obj.get("egress"),
            "logging": obj.get("logging"),
            "primaryCircuit": obj.get("primaryCircuit"),
            "primaryCircuitLabel": obj.get("primaryCircuitLabel"),
            "remark": ManaV2Dscp.from_dict(obj["remark"]) if obj.get("remark") is not None else None,
            "slaClass": obj.get("slaClass")
        })
        return _obj


