# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2Location(BaseModel):
    """
    ManaV2Location
    """ # noqa: E501
    address_line1: Optional[StrictStr] = Field(default=None, alias="addressLine1", json_schema_extra={"examples": ["example string"]})
    address_line2: Optional[StrictStr] = Field(default=None, alias="addressLine2", json_schema_extra={"examples": ["example string"]})
    city: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    country: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    country_code: Optional[StrictStr] = Field(default=None, alias="countryCode", json_schema_extra={"examples": ["example string"]})
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, json_schema_extra={"examples": [123.45]})
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, json_schema_extra={"examples": [123.45]})
    notes: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    province_code: Optional[StrictStr] = Field(default=None, alias="provinceCode", json_schema_extra={"examples": ["example string"]})
    state: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    state_code: Optional[StrictStr] = Field(default=None, alias="stateCode", json_schema_extra={"examples": ["example string"]})
    __properties: ClassVar[List[str]] = ["addressLine1", "addressLine2", "city", "country", "countryCode", "latitude", "longitude", "notes", "provinceCode", "state", "stateCode"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2Location from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2Location from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addressLine1": obj.get("addressLine1"),
            "addressLine2": obj.get("addressLine2"),
            "city": obj.get("city"),
            "country": obj.get("country"),
            "countryCode": obj.get("countryCode"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "notes": obj.get("notes"),
            "provinceCode": obj.get("provinceCode"),
            "state": obj.get("state"),
            "stateCode": obj.get("stateCode")
        })
        return _obj


