# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from graphiant_sdk.models.mana_v2_dscp import ManaV2Dscp
from graphiant_sdk.models.mana_v2_port_range import ManaV2PortRange
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2ForwardingPolicyMatch(BaseModel):
    """
    ManaV2ForwardingPolicyMatch
    """ # noqa: E501
    application: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    destination_network: Optional[StrictStr] = Field(default=None, alias="destinationNetwork", json_schema_extra={"examples": ["example string"]})
    destination_port: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="destinationPort", json_schema_extra={"examples": [123]})
    destination_port_range: Optional[ManaV2PortRange] = Field(default=None, alias="destinationPortRange")
    domain_category_ids: Optional[List[StrictInt]] = Field(default=None, alias="domainCategoryIds")
    domain_wildcards: Optional[List[StrictStr]] = Field(default=None, alias="domainWildcards")
    dscp: Optional[ManaV2Dscp] = None
    icmp_type: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="icmpType", json_schema_extra={"examples": [123]})
    ip_protocol: Optional[StrictStr] = Field(default=None, alias="ipProtocol", json_schema_extra={"examples": ["ENUM_VALUE"]})
    protocol: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ENUM_VALUE"]})
    source_network: Optional[StrictStr] = Field(default=None, alias="sourceNetwork", json_schema_extra={"examples": ["example string"]})
    source_port: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="sourcePort", json_schema_extra={"examples": [123]})
    source_port_range: Optional[ManaV2PortRange] = Field(default=None, alias="sourcePortRange")
    __properties: ClassVar[List[str]] = ["application", "destinationNetwork", "destinationPort", "destinationPortRange", "domainCategoryIds", "domainWildcards", "dscp", "icmpType", "ipProtocol", "protocol", "sourceNetwork", "sourcePort", "sourcePortRange"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2ForwardingPolicyMatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of destination_port_range
        if self.destination_port_range:
            _dict['destinationPortRange'] = self.destination_port_range.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dscp
        if self.dscp:
            _dict['dscp'] = self.dscp.to_dict()
        # override the default output from pydantic by calling `to_dict()` of source_port_range
        if self.source_port_range:
            _dict['sourcePortRange'] = self.source_port_range.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2ForwardingPolicyMatch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "application": obj.get("application"),
            "destinationNetwork": obj.get("destinationNetwork"),
            "destinationPort": obj.get("destinationPort"),
            "destinationPortRange": ManaV2PortRange.from_dict(obj["destinationPortRange"]) if obj.get("destinationPortRange") is not None else None,
            "domainCategoryIds": obj.get("domainCategoryIds"),
            "domainWildcards": obj.get("domainWildcards"),
            "dscp": ManaV2Dscp.from_dict(obj["dscp"]) if obj.get("dscp") is not None else None,
            "icmpType": obj.get("icmpType"),
            "ipProtocol": obj.get("ipProtocol"),
            "protocol": obj.get("protocol"),
            "sourceNetwork": obj.get("sourceNetwork"),
            "sourcePort": obj.get("sourcePort"),
            "sourcePortRange": ManaV2PortRange.from_dict(obj["sourcePortRange"]) if obj.get("sourcePortRange") is not None else None
        })
        return _obj


