# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2GlobalObjectSummary(BaseModel):
    """
    ManaV2GlobalObjectSummary
    """ # noqa: E501
    attach_point: Optional[StrictStr] = Field(default=None, alias="attachPoint", json_schema_extra={"examples": ["ENUM_VALUE"]})
    id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1234567891011]})
    ip_version: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="ipVersion", json_schema_extra={"examples": [123]})
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    num_attached_devices: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="numAttachedDevices", json_schema_extra={"examples": [123]})
    num_attached_sites: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="numAttachedSites", json_schema_extra={"examples": [123]})
    num_failures: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="numFailures", json_schema_extra={"examples": [123]})
    num_in_sync_devices: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="numInSyncDevices", json_schema_extra={"examples": [123]})
    num_override_devices: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="numOverrideDevices", json_schema_extra={"examples": [123]})
    num_policies: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="numPolicies", json_schema_extra={"examples": [123]})
    num_prefixes: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="numPrefixes", json_schema_extra={"examples": [123]})
    num_rules: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="numRules", json_schema_extra={"examples": [123]})
    num_statements: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="numStatements", json_schema_extra={"examples": [123]})
    traffic_policy_type: Optional[StrictStr] = Field(default=None, alias="trafficPolicyType", json_schema_extra={"examples": ["ENUM_VALUE"]})
    __properties: ClassVar[List[str]] = ["attachPoint", "id", "ipVersion", "name", "numAttachedDevices", "numAttachedSites", "numFailures", "numInSyncDevices", "numOverrideDevices", "numPolicies", "numPrefixes", "numRules", "numStatements", "trafficPolicyType"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2GlobalObjectSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2GlobalObjectSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attachPoint": obj.get("attachPoint"),
            "id": obj.get("id"),
            "ipVersion": obj.get("ipVersion"),
            "name": obj.get("name"),
            "numAttachedDevices": obj.get("numAttachedDevices"),
            "numAttachedSites": obj.get("numAttachedSites"),
            "numFailures": obj.get("numFailures"),
            "numInSyncDevices": obj.get("numInSyncDevices"),
            "numOverrideDevices": obj.get("numOverrideDevices"),
            "numPolicies": obj.get("numPolicies"),
            "numPrefixes": obj.get("numPrefixes"),
            "numRules": obj.get("numRules"),
            "numStatements": obj.get("numStatements"),
            "trafficPolicyType": obj.get("trafficPolicyType")
        })
        return _obj


