# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from graphiant_sdk.models.mana_v2_interface_address import ManaV2InterfaceAddress
from graphiant_sdk.models.mana_v2_interface_i_psec import ManaV2InterfaceIPsec
from graphiant_sdk.models.mana_v2_interface_ma_csec import ManaV2InterfaceMaCsec
from graphiant_sdk.models.mana_v2_interface_sfp_optical_strength import ManaV2InterfaceSfpOpticalStrength
from graphiant_sdk.models.mana_v2_interface_vlan import ManaV2InterfaceVlan
from graphiant_sdk.models.mana_v2_lag_interface import ManaV2LagInterface
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2Interface(BaseModel):
    """
    ManaV2Interface
    """ # noqa: E501
    alias: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    circuit: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    circuit_name: Optional[StrictStr] = Field(default=None, alias="circuitName", json_schema_extra={"examples": ["example string"]})
    config_updated_at: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="configUpdatedAt")
    configured_max_transmission_unit: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="configuredMaxTransmissionUnit", json_schema_extra={"examples": [123]})
    description: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    duplex: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    enabled: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    gateway_address_v4: Optional[StrictStr] = Field(default=None, alias="gatewayAddressV4", json_schema_extra={"examples": ["example string"]})
    gateway_address_v6: Optional[StrictStr] = Field(default=None, alias="gatewayAddressV6", json_schema_extra={"examples": ["example string"]})
    id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1234567891011]})
    ip_sec: Optional[ManaV2InterfaceIPsec] = Field(default=None, alias="ipSec")
    ipv4: Optional[ManaV2InterfaceAddress] = None
    ipv6: Optional[ManaV2InterfaceAddress] = None
    ipv6_addresses: Optional[List[ManaV2InterfaceAddress]] = Field(default=None, alias="ipv6Addresses")
    lag_interface: Optional[ManaV2LagInterface] = Field(default=None, alias="lagInterface")
    lan: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    lldp_enabled: Optional[StrictBool] = Field(default=None, alias="lldpEnabled", json_schema_extra={"examples": [True]})
    macsec: Optional[ManaV2InterfaceMaCsec] = None
    max_transmission_unit: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="maxTransmissionUnit", json_schema_extra={"examples": [123]})
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    oper_updated_at: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="operUpdatedAt")
    phy_address: Optional[StrictStr] = Field(default=None, alias="phyAddress", json_schema_extra={"examples": ["example string"]})
    protocol: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ENUM_VALUE"]})
    security_zone: Optional[StrictStr] = Field(default=None, alias="securityZone", json_schema_extra={"examples": ["example string"]})
    sfp_optical_strength: Optional[List[ManaV2InterfaceSfpOpticalStrength]] = Field(default=None, alias="sfpOpticalStrength")
    speed_mbps: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="speedMbps", json_schema_extra={"examples": [123]})
    subinterfaces: Optional[List[ManaV2InterfaceVlan]] = None
    tcp_mss: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="tcpMss", json_schema_extra={"examples": [123]})
    tcp_mss_v4: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="tcpMssV4", json_schema_extra={"examples": [123]})
    tcp_mss_v6: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="tcpMssV6", json_schema_extra={"examples": [123]})
    type: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ENUM_VALUE"]})
    up: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    vrf_function_id: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="vrfFunctionId", json_schema_extra={"examples": [123]})
    vrf_name: Optional[StrictStr] = Field(default=None, alias="vrfName", json_schema_extra={"examples": ["example string"]})
    __properties: ClassVar[List[str]] = ["alias", "circuit", "circuitName", "configUpdatedAt", "configuredMaxTransmissionUnit", "description", "duplex", "enabled", "gatewayAddressV4", "gatewayAddressV6", "id", "ipSec", "ipv4", "ipv6", "ipv6Addresses", "lagInterface", "lan", "lldpEnabled", "macsec", "maxTransmissionUnit", "name", "operUpdatedAt", "phyAddress", "protocol", "securityZone", "sfpOpticalStrength", "speedMbps", "subinterfaces", "tcpMss", "tcpMssV4", "tcpMssV6", "type", "up", "vrfFunctionId", "vrfName"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2Interface from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of config_updated_at
        if self.config_updated_at:
            _dict['configUpdatedAt'] = self.config_updated_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ip_sec
        if self.ip_sec:
            _dict['ipSec'] = self.ip_sec.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ipv4
        if self.ipv4:
            _dict['ipv4'] = self.ipv4.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ipv6
        if self.ipv6:
            _dict['ipv6'] = self.ipv6.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in ipv6_addresses (list)
        _items = []
        if self.ipv6_addresses:
            for _item_ipv6_addresses in self.ipv6_addresses:
                if _item_ipv6_addresses:
                    _items.append(_item_ipv6_addresses.to_dict())
            _dict['ipv6Addresses'] = _items
        # override the default output from pydantic by calling `to_dict()` of lag_interface
        if self.lag_interface:
            _dict['lagInterface'] = self.lag_interface.to_dict()
        # override the default output from pydantic by calling `to_dict()` of macsec
        if self.macsec:
            _dict['macsec'] = self.macsec.to_dict()
        # override the default output from pydantic by calling `to_dict()` of oper_updated_at
        if self.oper_updated_at:
            _dict['operUpdatedAt'] = self.oper_updated_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sfp_optical_strength (list)
        _items = []
        if self.sfp_optical_strength:
            for _item_sfp_optical_strength in self.sfp_optical_strength:
                if _item_sfp_optical_strength:
                    _items.append(_item_sfp_optical_strength.to_dict())
            _dict['sfpOpticalStrength'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in subinterfaces (list)
        _items = []
        if self.subinterfaces:
            for _item_subinterfaces in self.subinterfaces:
                if _item_subinterfaces:
                    _items.append(_item_subinterfaces.to_dict())
            _dict['subinterfaces'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2Interface from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alias": obj.get("alias"),
            "circuit": obj.get("circuit"),
            "circuitName": obj.get("circuitName"),
            "configUpdatedAt": GoogleProtobufTimestamp.from_dict(obj["configUpdatedAt"]) if obj.get("configUpdatedAt") is not None else None,
            "configuredMaxTransmissionUnit": obj.get("configuredMaxTransmissionUnit"),
            "description": obj.get("description"),
            "duplex": obj.get("duplex"),
            "enabled": obj.get("enabled"),
            "gatewayAddressV4": obj.get("gatewayAddressV4"),
            "gatewayAddressV6": obj.get("gatewayAddressV6"),
            "id": obj.get("id"),
            "ipSec": ManaV2InterfaceIPsec.from_dict(obj["ipSec"]) if obj.get("ipSec") is not None else None,
            "ipv4": ManaV2InterfaceAddress.from_dict(obj["ipv4"]) if obj.get("ipv4") is not None else None,
            "ipv6": ManaV2InterfaceAddress.from_dict(obj["ipv6"]) if obj.get("ipv6") is not None else None,
            "ipv6Addresses": [ManaV2InterfaceAddress.from_dict(_item) for _item in obj["ipv6Addresses"]] if obj.get("ipv6Addresses") is not None else None,
            "lagInterface": ManaV2LagInterface.from_dict(obj["lagInterface"]) if obj.get("lagInterface") is not None else None,
            "lan": obj.get("lan"),
            "lldpEnabled": obj.get("lldpEnabled"),
            "macsec": ManaV2InterfaceMaCsec.from_dict(obj["macsec"]) if obj.get("macsec") is not None else None,
            "maxTransmissionUnit": obj.get("maxTransmissionUnit"),
            "name": obj.get("name"),
            "operUpdatedAt": GoogleProtobufTimestamp.from_dict(obj["operUpdatedAt"]) if obj.get("operUpdatedAt") is not None else None,
            "phyAddress": obj.get("phyAddress"),
            "protocol": obj.get("protocol"),
            "securityZone": obj.get("securityZone"),
            "sfpOpticalStrength": [ManaV2InterfaceSfpOpticalStrength.from_dict(_item) for _item in obj["sfpOpticalStrength"]] if obj.get("sfpOpticalStrength") is not None else None,
            "speedMbps": obj.get("speedMbps"),
            "subinterfaces": [ManaV2InterfaceVlan.from_dict(_item) for _item in obj["subinterfaces"]] if obj.get("subinterfaces") is not None else None,
            "tcpMss": obj.get("tcpMss"),
            "tcpMssV4": obj.get("tcpMssV4"),
            "tcpMssV6": obj.get("tcpMssV6"),
            "type": obj.get("type"),
            "up": obj.get("up"),
            "vrfFunctionId": obj.get("vrfFunctionId"),
            "vrfName": obj.get("vrfName")
        })
        return _obj


