# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from graphiant_sdk.models.mana_v2_ip_network_list_config import ManaV2IpNetworkListConfig
from graphiant_sdk.models.mana_v2_l4_port_list_config import ManaV2L4PortListConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2DpiApplicationConfig(BaseModel):
    """
    ManaV2DpiApplicationConfig
    """ # noqa: E501
    description: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    destination_network: Optional[StrictStr] = Field(default=None, alias="destinationNetwork", json_schema_extra={"examples": ["example string"]})
    destination_network_list: Optional[StrictStr] = Field(default=None, alias="destinationNetworkList", json_schema_extra={"examples": ["example string"]})
    destination_networks: Optional[ManaV2IpNetworkListConfig] = Field(default=None, alias="destinationNetworks")
    destination_port: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="destinationPort", json_schema_extra={"examples": [123]})
    destination_port_list: Optional[StrictStr] = Field(default=None, alias="destinationPortList", json_schema_extra={"examples": ["example string"]})
    destination_ports: Optional[ManaV2L4PortListConfig] = Field(default=None, alias="destinationPorts")
    icmp_type: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="icmpType", json_schema_extra={"examples": [123]})
    ip_protocol: Optional[StrictStr] = Field(default=None, alias="ipProtocol", json_schema_extra={"examples": ["ENUM_VALUE"]})
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    source_network: Optional[StrictStr] = Field(default=None, alias="sourceNetwork", json_schema_extra={"examples": ["example string"]})
    source_network_list: Optional[StrictStr] = Field(default=None, alias="sourceNetworkList", json_schema_extra={"examples": ["example string"]})
    source_networks: Optional[ManaV2IpNetworkListConfig] = Field(default=None, alias="sourceNetworks")
    source_port: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="sourcePort", json_schema_extra={"examples": [123]})
    source_port_list: Optional[StrictStr] = Field(default=None, alias="sourcePortList", json_schema_extra={"examples": ["example string"]})
    source_ports: Optional[ManaV2L4PortListConfig] = Field(default=None, alias="sourcePorts")
    __properties: ClassVar[List[str]] = ["description", "destinationNetwork", "destinationNetworkList", "destinationNetworks", "destinationPort", "destinationPortList", "destinationPorts", "icmpType", "ipProtocol", "name", "sourceNetwork", "sourceNetworkList", "sourceNetworks", "sourcePort", "sourcePortList", "sourcePorts"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2DpiApplicationConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of destination_networks
        if self.destination_networks:
            _dict['destinationNetworks'] = self.destination_networks.to_dict()
        # override the default output from pydantic by calling `to_dict()` of destination_ports
        if self.destination_ports:
            _dict['destinationPorts'] = self.destination_ports.to_dict()
        # override the default output from pydantic by calling `to_dict()` of source_networks
        if self.source_networks:
            _dict['sourceNetworks'] = self.source_networks.to_dict()
        # override the default output from pydantic by calling `to_dict()` of source_ports
        if self.source_ports:
            _dict['sourcePorts'] = self.source_ports.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2DpiApplicationConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "description": obj.get("description"),
            "destinationNetwork": obj.get("destinationNetwork"),
            "destinationNetworkList": obj.get("destinationNetworkList"),
            "destinationNetworks": ManaV2IpNetworkListConfig.from_dict(obj["destinationNetworks"]) if obj.get("destinationNetworks") is not None else None,
            "destinationPort": obj.get("destinationPort"),
            "destinationPortList": obj.get("destinationPortList"),
            "destinationPorts": ManaV2L4PortListConfig.from_dict(obj["destinationPorts"]) if obj.get("destinationPorts") is not None else None,
            "icmpType": obj.get("icmpType"),
            "ipProtocol": obj.get("ipProtocol"),
            "name": obj.get("name"),
            "sourceNetwork": obj.get("sourceNetwork"),
            "sourceNetworkList": obj.get("sourceNetworkList"),
            "sourceNetworks": ManaV2IpNetworkListConfig.from_dict(obj["sourceNetworks"]) if obj.get("sourceNetworks") is not None else None,
            "sourcePort": obj.get("sourcePort"),
            "sourcePortList": obj.get("sourcePortList"),
            "sourcePorts": ManaV2L4PortListConfig.from_dict(obj["sourcePorts"]) if obj.get("sourcePorts") is not None else None
        })
        return _obj


