# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.mana_v2_security_policy_rule import ManaV2SecurityPolicyRule
from graphiant_sdk.models.mana_v2_traffic_policy_rule import ManaV2TrafficPolicyRule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2PublicVifConsumerLanSegmentResponse(BaseModel):
    """
    ManaV2PublicVifConsumerLanSegmentResponse
    """ # noqa: E501
    allowed_prefixes: Optional[List[StrictStr]] = Field(default=None, alias="allowedPrefixes")
    outbound_security_rules: Optional[List[ManaV2SecurityPolicyRule]] = Field(default=None, alias="outboundSecurityRules")
    service_lan_segment: Optional[StrictInt] = Field(default=None, description="LAN segment ID for the service", alias="serviceLanSegment", json_schema_extra={"examples": [1234567891011]})
    traffic_rules: Optional[List[ManaV2TrafficPolicyRule]] = Field(default=None, alias="trafficRules")
    __properties: ClassVar[List[str]] = ["allowedPrefixes", "outboundSecurityRules", "serviceLanSegment", "trafficRules"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2PublicVifConsumerLanSegmentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in outbound_security_rules (list)
        _items = []
        if self.outbound_security_rules:
            for _item_outbound_security_rules in self.outbound_security_rules:
                if _item_outbound_security_rules:
                    _items.append(_item_outbound_security_rules.to_dict())
            _dict['outboundSecurityRules'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in traffic_rules (list)
        _items = []
        if self.traffic_rules:
            for _item_traffic_rules in self.traffic_rules:
                if _item_traffic_rules:
                    _items.append(_item_traffic_rules.to_dict())
            _dict['trafficRules'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2PublicVifConsumerLanSegmentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowedPrefixes": obj.get("allowedPrefixes"),
            "outboundSecurityRules": [ManaV2SecurityPolicyRule.from_dict(_item) for _item in obj["outboundSecurityRules"]] if obj.get("outboundSecurityRules") is not None else None,
            "serviceLanSegment": obj.get("serviceLanSegment"),
            "trafficRules": [ManaV2TrafficPolicyRule.from_dict(_item) for _item in obj["trafficRules"]] if obj.get("trafficRules") is not None else None
        })
        return _obj


