# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from graphiant_sdk.models.mana_v2_public_vif_consumer_lan_segment import ManaV2PublicVifConsumerLanSegment
from graphiant_sdk.models.mana_v2_site_information import ManaV2SiteInformation
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2PublicVifConsumerPolicy(BaseModel):
    """
    ManaV2PublicVifConsumerPolicy
    """ # noqa: E501
    lan_segments: List[ManaV2PublicVifConsumerLanSegment] = Field(alias="lanSegments")
    sites: ManaV2SiteInformation
    __properties: ClassVar[List[str]] = ["lanSegments", "sites"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2PublicVifConsumerPolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in lan_segments (list)
        _items = []
        if self.lan_segments:
            for _item_lan_segments in self.lan_segments:
                if _item_lan_segments:
                    _items.append(_item_lan_segments.to_dict())
            _dict['lanSegments'] = _items
        # override the default output from pydantic by calling `to_dict()` of sites
        if self.sites:
            _dict['sites'] = self.sites.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2PublicVifConsumerPolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lanSegments": [ManaV2PublicVifConsumerLanSegment.from_dict(_item) for _item in obj["lanSegments"]] if obj.get("lanSegments") is not None else None,
            "sites": ManaV2SiteInformation.from_dict(obj["sites"]) if obj.get("sites") is not None else None
        })
        return _obj


