# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2IpfixExporter(BaseModel):
    """
    ManaV2IpfixExporter
    """ # noqa: E501
    destination_address: Optional[StrictStr] = Field(default=None, alias="destinationAddress", json_schema_extra={"examples": ["example string"]})
    destination_port: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="destinationPort", json_schema_extra={"examples": [123]})
    error_message: Optional[StrictStr] = Field(default=None, alias="errorMessage", json_schema_extra={"examples": ["example string"]})
    global_id: Optional[StrictInt] = Field(default=None, alias="globalId", json_schema_extra={"examples": [1234567891011]})
    id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1234567891011]})
    monitored_segments: Optional[List[StrictStr]] = Field(default=None, alias="monitoredSegments")
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    sample_mode: Optional[StrictStr] = Field(default=None, alias="sampleMode", json_schema_extra={"examples": ["example string"]})
    sample_rate: Optional[StrictInt] = Field(default=None, alias="sampleRate", json_schema_extra={"examples": [1234567891011]})
    source_address: Optional[StrictStr] = Field(default=None, alias="sourceAddress", json_schema_extra={"examples": ["example string"]})
    source_interface: Optional[StrictStr] = Field(default=None, alias="sourceInterface", json_schema_extra={"examples": ["example string"]})
    source_segment: Optional[StrictStr] = Field(default=None, alias="sourceSegment", json_schema_extra={"examples": ["example string"]})
    status: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ENUM_VALUE"]})
    vrf_id: Optional[StrictInt] = Field(default=None, alias="vrfId", json_schema_extra={"examples": [1234567891011]})
    vrf_name: Optional[StrictStr] = Field(default=None, alias="vrfName", json_schema_extra={"examples": ["example string"]})
    __properties: ClassVar[List[str]] = ["destinationAddress", "destinationPort", "errorMessage", "globalId", "id", "monitoredSegments", "name", "sampleMode", "sampleRate", "sourceAddress", "sourceInterface", "sourceSegment", "status", "vrfId", "vrfName"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2IpfixExporter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2IpfixExporter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "destinationAddress": obj.get("destinationAddress"),
            "destinationPort": obj.get("destinationPort"),
            "errorMessage": obj.get("errorMessage"),
            "globalId": obj.get("globalId"),
            "id": obj.get("id"),
            "monitoredSegments": obj.get("monitoredSegments"),
            "name": obj.get("name"),
            "sampleMode": obj.get("sampleMode"),
            "sampleRate": obj.get("sampleRate"),
            "sourceAddress": obj.get("sourceAddress"),
            "sourceInterface": obj.get("sourceInterface"),
            "sourceSegment": obj.get("sourceSegment"),
            "status": obj.get("status"),
            "vrfId": obj.get("vrfId"),
            "vrfName": obj.get("vrfName")
        })
        return _obj


