# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from graphiant_sdk.models.mana_v2_i_psec_gateway_tunnel_details import ManaV2IPsecGatewayTunnelDetails
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2IPsecGatewayRemotePeer(BaseModel):
    """
    ManaV2IPsecGatewayRemotePeer
    """ # noqa: E501
    destination_address: Optional[StrictStr] = Field(default=None, alias="destinationAddress", json_schema_extra={"examples": ["example string"]})
    ike_initiator: Optional[StrictBool] = Field(default=None, description="When true, Graphiant initiates IKE for this peer", alias="ikeInitiator", json_schema_extra={"examples": [True]})
    mtu: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, json_schema_extra={"examples": [123]})
    name: Optional[StrictStr] = Field(default=None, description="Optional display name or label for this peer; used when generating tunnel names", json_schema_extra={"examples": ["example string"]})
    remote_ike_peer_identity: Optional[StrictStr] = Field(default=None, description="IKE identity of the remote peer", alias="remoteIkePeerIdentity", json_schema_extra={"examples": ["example string"]})
    tcp_mss: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="tcpMss", json_schema_extra={"examples": [123]})
    tunnel1: Optional[ManaV2IPsecGatewayTunnelDetails] = None
    tunnel2: Optional[ManaV2IPsecGatewayTunnelDetails] = None
    vpn_profile: Optional[StrictStr] = Field(default=None, description="Enterprise IPsec VPN profile name for this peer", alias="vpnProfile", json_schema_extra={"examples": ["example string"]})
    __properties: ClassVar[List[str]] = ["destinationAddress", "ikeInitiator", "mtu", "name", "remoteIkePeerIdentity", "tcpMss", "tunnel1", "tunnel2", "vpnProfile"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2IPsecGatewayRemotePeer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tunnel1
        if self.tunnel1:
            _dict['tunnel1'] = self.tunnel1.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tunnel2
        if self.tunnel2:
            _dict['tunnel2'] = self.tunnel2.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2IPsecGatewayRemotePeer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "destinationAddress": obj.get("destinationAddress"),
            "ikeInitiator": obj.get("ikeInitiator"),
            "mtu": obj.get("mtu"),
            "name": obj.get("name"),
            "remoteIkePeerIdentity": obj.get("remoteIkePeerIdentity"),
            "tcpMss": obj.get("tcpMss"),
            "tunnel1": ManaV2IPsecGatewayTunnelDetails.from_dict(obj["tunnel1"]) if obj.get("tunnel1") is not None else None,
            "tunnel2": ManaV2IPsecGatewayTunnelDetails.from_dict(obj["tunnel2"]) if obj.get("tunnel2") is not None else None,
            "vpnProfile": obj.get("vpnProfile")
        })
        return _obj


