# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from graphiant_sdk.models.mana_v2_ospf_area import ManaV2OspfArea
from graphiant_sdk.models.mana_v2_ospf_redistribute import ManaV2OspfRedistribute
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManaV2OspFv3Process(BaseModel):
    """
    ManaV2OspFv3Process
    """ # noqa: E501
    admin_distance: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Administrative Distance for routes installed", alias="adminDistance", json_schema_extra={"examples": [100]})
    areas: Optional[List[ManaV2OspfArea]] = None
    default_originate: Optional[StrictStr] = Field(default=None, alias="defaultOriginate", json_schema_extra={"examples": ["ENUM_VALUE"]})
    id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1234567891011]})
    redistributed_protocols: Optional[List[ManaV2OspfRedistribute]] = Field(default=None, alias="redistributedProtocols")
    router_id: Optional[StrictStr] = Field(default=None, alias="routerId", json_schema_extra={"examples": ["example string"]})
    version: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, json_schema_extra={"examples": [123]})
    __properties: ClassVar[List[str]] = ["adminDistance", "areas", "defaultOriginate", "id", "redistributedProtocols", "routerId", "version"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2OspFv3Process from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in areas (list)
        _items = []
        if self.areas:
            for _item_areas in self.areas:
                if _item_areas:
                    _items.append(_item_areas.to_dict())
            _dict['areas'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in redistributed_protocols (list)
        _items = []
        if self.redistributed_protocols:
            for _item_redistributed_protocols in self.redistributed_protocols:
                if _item_redistributed_protocols:
                    _items.append(_item_redistributed_protocols.to_dict())
            _dict['redistributedProtocols'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2OspFv3Process from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "adminDistance": obj.get("adminDistance"),
            "areas": [ManaV2OspfArea.from_dict(_item) for _item in obj["areas"]] if obj.get("areas") is not None else None,
            "defaultOriginate": obj.get("defaultOriginate"),
            "id": obj.get("id"),
            "redistributedProtocols": [ManaV2OspfRedistribute.from_dict(_item) for _item in obj["redistributedProtocols"]] if obj.get("redistributedProtocols") is not None else None,
            "routerId": obj.get("routerId"),
            "version": obj.get("version")
        })
        return _obj


