# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PokedexDeviceMappingInfo(BaseModel):
    """
    PokedexDeviceMappingInfo
    """ # noqa: E501
    connect_time: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="connectTime")
    device_id: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="deviceId", json_schema_extra={"examples": [12345678910]})
    enterprise_id: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="enterpriseId", json_schema_extra={"examples": [12345678910]})
    hostname: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    ipaddress: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    tt_identity: Optional[StrictStr] = Field(default=None, alias="ttIdentity", json_schema_extra={"examples": ["example string"]})
    __properties: ClassVar[List[str]] = ["connectTime", "deviceId", "enterpriseId", "hostname", "ipaddress", "ttIdentity"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PokedexDeviceMappingInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of connect_time
        if self.connect_time:
            _dict['connectTime'] = self.connect_time.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PokedexDeviceMappingInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "connectTime": GoogleProtobufTimestamp.from_dict(obj["connectTime"]) if obj.get("connectTime") is not None else None,
            "deviceId": obj.get("deviceId"),
            "enterpriseId": obj.get("enterpriseId"),
            "hostname": obj.get("hostname"),
            "ipaddress": obj.get("ipaddress"),
            "ttIdentity": obj.get("ttIdentity")
        })
        return _obj


