# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RoutingPrefixFilter(BaseModel):
    """
    RoutingPrefixFilter
    """ # noqa: E501
    as_path: Optional[List[StrictStr]] = Field(default=None, alias="asPath")
    ext_community: Optional[StrictStr] = Field(default=None, alias="extCommunity", json_schema_extra={"examples": ["example string"]})
    interface_name: Optional[StrictStr] = Field(default=None, description="Interface name", alias="interfaceName", json_schema_extra={"examples": ["ethernet1/0"]})
    next_hop: Optional[StrictStr] = Field(default=None, description="IPv4 or IPv6 Nexthop", alias="nextHop", json_schema_extra={"examples": ["10.1.1.1"]})
    prefix: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    rd: Optional[StrictStr] = Field(default=None, description="Route RD. Must for BGPAddrFamilyVpnIpv4Unicast/BGPAddrFamilyVpnIpv6Unicast", json_schema_extra={"examples": ["10:1231"]})
    src_proto: Optional[StrictStr] = Field(default=None, alias="srcProto", json_schema_extra={"examples": ["example string"]})
    type: Optional[StrictStr] = Field(default=None, description="route type", json_schema_extra={"examples": ["internal or external"]})
    __properties: ClassVar[List[str]] = ["asPath", "extCommunity", "interfaceName", "nextHop", "prefix", "rd", "srcProto", "type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RoutingPrefixFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RoutingPrefixFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "asPath": obj.get("asPath"),
            "extCommunity": obj.get("extCommunity"),
            "interfaceName": obj.get("interfaceName"),
            "nextHop": obj.get("nextHop"),
            "prefix": obj.get("prefix"),
            "rd": obj.get("rd"),
            "srcProto": obj.get("srcProto"),
            "type": obj.get("type")
        })
        return _obj


