# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from graphiant_sdk.models.mana_v2_location import ManaV2Location
from graphiant_sdk.models.upgrade_upgrade_summary import UpgradeUpgradeSummary
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SearchEdgeSummary(BaseModel):
    """
    SearchEdgeSummary
    """ # noqa: E501
    assigned_on: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="assignedOn")
    canary_mode: Optional[StrictStr] = Field(default=None, alias="canaryMode", json_schema_extra={"examples": ["ENUM_VALUE"]})
    connected_regions: Optional[List[StrictStr]] = Field(default=None, alias="connectedRegions")
    device_id: Optional[StrictInt] = Field(default=None, alias="deviceId", json_schema_extra={"examples": [1234567891011]})
    discovered_location: Optional[StrictStr] = Field(default=None, alias="discoveredLocation", json_schema_extra={"examples": ["example string"]})
    enterprise_id: Optional[StrictInt] = Field(default=None, alias="enterpriseId", json_schema_extra={"examples": [1234567891011]})
    enterprise_name: Optional[StrictStr] = Field(default=None, alias="enterpriseName", json_schema_extra={"examples": ["example string"]})
    first_appeared_on: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="firstAppearedOn")
    hostname: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    ip_detected: Optional[StrictStr] = Field(default=None, alias="ipDetected", json_schema_extra={"examples": ["example string"]})
    is_hardware: Optional[StrictBool] = Field(default=None, alias="isHardware", json_schema_extra={"examples": [True]})
    is_new: Optional[StrictBool] = Field(default=None, alias="isNew", json_schema_extra={"examples": [True]})
    is_requested: Optional[StrictBool] = Field(default=None, alias="isRequested", json_schema_extra={"examples": [True]})
    is_requested_status: Optional[StrictStr] = Field(default=None, alias="isRequestedStatus", json_schema_extra={"examples": ["ENUM_VALUE"]})
    last_booted_at: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="lastBootedAt")
    location: Optional[ManaV2Location] = None
    model: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    override_region: Optional[StrictStr] = Field(default=None, alias="overrideRegion", json_schema_extra={"examples": ["example string"]})
    parent_enterprise_name: Optional[StrictStr] = Field(default=None, alias="parentEnterpriseName", json_schema_extra={"examples": ["example string"]})
    portal_status: Optional[StrictStr] = Field(default=None, alias="portalStatus", json_schema_extra={"examples": ["ENUM_VALUE"]})
    region: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    role: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ENUM_VALUE"]})
    serial_num: Optional[StrictStr] = Field(default=None, alias="serialNum", json_schema_extra={"examples": ["example string"]})
    site: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    site_id: Optional[StrictInt] = Field(default=None, alias="siteId", json_schema_extra={"examples": [1234567891011]})
    stale: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    status: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ENUM_VALUE"]})
    sw_name: Optional[StrictStr] = Field(default=None, alias="swName", json_schema_extra={"examples": ["example string"]})
    sw_version: Optional[StrictStr] = Field(default=None, alias="swVersion", json_schema_extra={"examples": ["example string"]})
    tt_conn_count: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="ttConnCount", json_schema_extra={"examples": [123]})
    upgrade_summary: Optional[UpgradeUpgradeSummary] = Field(default=None, alias="upgradeSummary")
    __properties: ClassVar[List[str]] = ["assignedOn", "canaryMode", "connectedRegions", "deviceId", "discoveredLocation", "enterpriseId", "enterpriseName", "firstAppearedOn", "hostname", "ipDetected", "isHardware", "isNew", "isRequested", "isRequestedStatus", "lastBootedAt", "location", "model", "overrideRegion", "parentEnterpriseName", "portalStatus", "region", "role", "serialNum", "site", "siteId", "stale", "status", "swName", "swVersion", "ttConnCount", "upgradeSummary"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchEdgeSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of assigned_on
        if self.assigned_on:
            _dict['assignedOn'] = self.assigned_on.to_dict()
        # override the default output from pydantic by calling `to_dict()` of first_appeared_on
        if self.first_appeared_on:
            _dict['firstAppearedOn'] = self.first_appeared_on.to_dict()
        # override the default output from pydantic by calling `to_dict()` of last_booted_at
        if self.last_booted_at:
            _dict['lastBootedAt'] = self.last_booted_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of upgrade_summary
        if self.upgrade_summary:
            _dict['upgradeSummary'] = self.upgrade_summary.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchEdgeSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "assignedOn": GoogleProtobufTimestamp.from_dict(obj["assignedOn"]) if obj.get("assignedOn") is not None else None,
            "canaryMode": obj.get("canaryMode"),
            "connectedRegions": obj.get("connectedRegions"),
            "deviceId": obj.get("deviceId"),
            "discoveredLocation": obj.get("discoveredLocation"),
            "enterpriseId": obj.get("enterpriseId"),
            "enterpriseName": obj.get("enterpriseName"),
            "firstAppearedOn": GoogleProtobufTimestamp.from_dict(obj["firstAppearedOn"]) if obj.get("firstAppearedOn") is not None else None,
            "hostname": obj.get("hostname"),
            "ipDetected": obj.get("ipDetected"),
            "isHardware": obj.get("isHardware"),
            "isNew": obj.get("isNew"),
            "isRequested": obj.get("isRequested"),
            "isRequestedStatus": obj.get("isRequestedStatus"),
            "lastBootedAt": GoogleProtobufTimestamp.from_dict(obj["lastBootedAt"]) if obj.get("lastBootedAt") is not None else None,
            "location": ManaV2Location.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "model": obj.get("model"),
            "overrideRegion": obj.get("overrideRegion"),
            "parentEnterpriseName": obj.get("parentEnterpriseName"),
            "portalStatus": obj.get("portalStatus"),
            "region": obj.get("region"),
            "role": obj.get("role"),
            "serialNum": obj.get("serialNum"),
            "site": obj.get("site"),
            "siteId": obj.get("siteId"),
            "stale": obj.get("stale"),
            "status": obj.get("status"),
            "swName": obj.get("swName"),
            "swVersion": obj.get("swVersion"),
            "ttConnCount": obj.get("ttConnCount"),
            "upgradeSummary": UpgradeUpgradeSummary.from_dict(obj["upgradeSummary"]) if obj.get("upgradeSummary") is not None else None
        })
        return _obj


