# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StatsmonTroubleshootingIssue(BaseModel):
    """
    StatsmonTroubleshootingIssue
    """ # noqa: E501
    alert_id: Optional[StrictStr] = Field(default=None, alias="alertId", json_schema_extra={"examples": ["example string"]})
    allow_listed: Optional[StrictBool] = Field(default=None, alias="allowListed", json_schema_extra={"examples": [True]})
    component: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    end_time: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="endTime")
    entity: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    issue: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    mute_listed: Optional[StrictBool] = Field(default=None, alias="muteListed", json_schema_extra={"examples": [True]})
    notification_created: Optional[StrictBool] = Field(default=None, alias="notificationCreated", json_schema_extra={"examples": [True]})
    plane: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    reason: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    severity: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ENUM_VALUE"]})
    start_time: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="startTime")
    status: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ENUM_VALUE"]})
    __properties: ClassVar[List[str]] = ["alertId", "allowListed", "component", "endTime", "entity", "issue", "muteListed", "notificationCreated", "plane", "reason", "severity", "startTime", "status"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatsmonTroubleshootingIssue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of end_time
        if self.end_time:
            _dict['endTime'] = self.end_time.to_dict()
        # override the default output from pydantic by calling `to_dict()` of start_time
        if self.start_time:
            _dict['startTime'] = self.start_time.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatsmonTroubleshootingIssue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alertId": obj.get("alertId"),
            "allowListed": obj.get("allowListed"),
            "component": obj.get("component"),
            "endTime": GoogleProtobufTimestamp.from_dict(obj["endTime"]) if obj.get("endTime") is not None else None,
            "entity": obj.get("entity"),
            "issue": obj.get("issue"),
            "muteListed": obj.get("muteListed"),
            "notificationCreated": obj.get("notificationCreated"),
            "plane": obj.get("plane"),
            "reason": obj.get("reason"),
            "severity": obj.get("severity"),
            "startTime": GoogleProtobufTimestamp.from_dict(obj["startTime"]) if obj.get("startTime") is not None else None,
            "status": obj.get("status")
        })
        return _obj


