# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StatsmonV2Connection(BaseModel):
    """
    StatsmonV2Connection
    """ # noqa: E501
    active: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    circuit_carrier: Optional[StrictStr] = Field(default=None, alias="circuitCarrier", json_schema_extra={"examples": ["example string"]})
    circuit_name: Optional[StrictStr] = Field(default=None, alias="circuitName", json_schema_extra={"examples": ["example string"]})
    destination_ip: Optional[StrictStr] = Field(default=None, alias="destinationIp", json_schema_extra={"examples": ["example string"]})
    hostname: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    last_established_time: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="lastEstablishedTime")
    last_resort: Optional[StrictBool] = Field(default=None, alias="lastResort", json_schema_extra={"examples": [True]})
    quality: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ENUM_VALUE"]})
    source_ip: Optional[StrictStr] = Field(default=None, alias="sourceIp", json_schema_extra={"examples": ["example string"]})
    source_public_ip: Optional[StrictStr] = Field(default=None, alias="sourcePublicIp", json_schema_extra={"examples": ["example string"]})
    __properties: ClassVar[List[str]] = ["active", "circuitCarrier", "circuitName", "destinationIp", "hostname", "lastEstablishedTime", "lastResort", "quality", "sourceIp", "sourcePublicIp"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatsmonV2Connection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of last_established_time
        if self.last_established_time:
            _dict['lastEstablishedTime'] = self.last_established_time.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatsmonV2Connection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "circuitCarrier": obj.get("circuitCarrier"),
            "circuitName": obj.get("circuitName"),
            "destinationIp": obj.get("destinationIp"),
            "hostname": obj.get("hostname"),
            "lastEstablishedTime": GoogleProtobufTimestamp.from_dict(obj["lastEstablishedTime"]) if obj.get("lastEstablishedTime") is not None else None,
            "lastResort": obj.get("lastResort"),
            "quality": obj.get("quality"),
            "sourceIp": obj.get("sourceIp"),
            "sourcePublicIp": obj.get("sourcePublicIp")
        })
        return _obj


