# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from graphiant_sdk.models.statsmon_bandwidthtracker_bw_usage_by_role_summary import StatsmonBandwidthtrackerBwUsageByRoleSummary
from graphiant_sdk.models.statsmon_bandwidthtracker_bw_usage_by_top_regions import StatsmonBandwidthtrackerBwUsageByTopRegions
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StatsmonBandwidthtrackerBwUsageByEnterpriseSummary(BaseModel):
    """
    StatsmonBandwidthtrackerBwUsageByEnterpriseSummary
    """ # noqa: E501
    bwusage_role_summary: Optional[List[StatsmonBandwidthtrackerBwUsageByRoleSummary]] = Field(default=None, alias="bwusageRoleSummary")
    bwusage_top_regions: Optional[List[StatsmonBandwidthtrackerBwUsageByTopRegions]] = Field(default=None, alias="bwusageTopRegions")
    min_time: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="minTime")
    percent_changed: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="percentChanged", json_schema_extra={"examples": [123.45]})
    provider_count: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="providerCount", json_schema_extra={"examples": [12345678910]})
    region_count: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="regionCount", json_schema_extra={"examples": [12345678910]})
    site_count: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="siteCount", json_schema_extra={"examples": [12345678910]})
    usage_kbps: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="usageKbps", json_schema_extra={"examples": [123.45]})
    __properties: ClassVar[List[str]] = ["bwusageRoleSummary", "bwusageTopRegions", "minTime", "percentChanged", "providerCount", "regionCount", "siteCount", "usageKbps"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatsmonBandwidthtrackerBwUsageByEnterpriseSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bwusage_role_summary (list)
        _items = []
        if self.bwusage_role_summary:
            for _item_bwusage_role_summary in self.bwusage_role_summary:
                if _item_bwusage_role_summary:
                    _items.append(_item_bwusage_role_summary.to_dict())
            _dict['bwusageRoleSummary'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in bwusage_top_regions (list)
        _items = []
        if self.bwusage_top_regions:
            for _item_bwusage_top_regions in self.bwusage_top_regions:
                if _item_bwusage_top_regions:
                    _items.append(_item_bwusage_top_regions.to_dict())
            _dict['bwusageTopRegions'] = _items
        # override the default output from pydantic by calling `to_dict()` of min_time
        if self.min_time:
            _dict['minTime'] = self.min_time.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatsmonBandwidthtrackerBwUsageByEnterpriseSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bwusageRoleSummary": [StatsmonBandwidthtrackerBwUsageByRoleSummary.from_dict(_item) for _item in obj["bwusageRoleSummary"]] if obj.get("bwusageRoleSummary") is not None else None,
            "bwusageTopRegions": [StatsmonBandwidthtrackerBwUsageByTopRegions.from_dict(_item) for _item in obj["bwusageTopRegions"]] if obj.get("bwusageTopRegions") is not None else None,
            "minTime": GoogleProtobufTimestamp.from_dict(obj["minTime"]) if obj.get("minTime") is not None else None,
            "percentChanged": obj.get("percentChanged"),
            "providerCount": obj.get("providerCount"),
            "regionCount": obj.get("regionCount"),
            "siteCount": obj.get("siteCount"),
            "usageKbps": obj.get("usageKbps")
        })
        return _obj


