# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from graphiant_sdk.models.upgrade_rollout_config import UpgradeRolloutConfig
from graphiant_sdk.models.upgrade_rollout_device import UpgradeRolloutDevice
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpgradeRollout(BaseModel):
    """
    UpgradeRollout
    """ # noqa: E501
    devices: Optional[List[UpgradeRolloutDevice]] = None
    has_failed: Optional[StrictBool] = Field(default=None, description="True if any device in the rollout has a failed upgrade state.", alias="hasFailed", json_schema_extra={"examples": [True]})
    id: Optional[StrictInt] = Field(default=None, description="Server-assigned rollout identifier.", json_schema_extra={"examples": [42]})
    last_run_ts: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="lastRunTs")
    next_run_ts: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="nextRunTs")
    num_devices: Optional[StrictInt] = Field(default=None, description="Count of devices associated with the rollout.", alias="numDevices", json_schema_extra={"examples": [3]})
    rollout_config: Optional[UpgradeRolloutConfig] = Field(default=None, alias="rolloutConfig")
    status: Optional[StrictStr] = Field(default=None, description="Status of the upgrade rollout group", json_schema_extra={"examples": ["idle"]})
    __properties: ClassVar[List[str]] = ["devices", "hasFailed", "id", "lastRunTs", "nextRunTs", "numDevices", "rolloutConfig", "status"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpgradeRollout from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in devices (list)
        _items = []
        if self.devices:
            for _item_devices in self.devices:
                if _item_devices:
                    _items.append(_item_devices.to_dict())
            _dict['devices'] = _items
        # override the default output from pydantic by calling `to_dict()` of last_run_ts
        if self.last_run_ts:
            _dict['lastRunTs'] = self.last_run_ts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of next_run_ts
        if self.next_run_ts:
            _dict['nextRunTs'] = self.next_run_ts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rollout_config
        if self.rollout_config:
            _dict['rolloutConfig'] = self.rollout_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpgradeRollout from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "devices": [UpgradeRolloutDevice.from_dict(_item) for _item in obj["devices"]] if obj.get("devices") is not None else None,
            "hasFailed": obj.get("hasFailed"),
            "id": obj.get("id"),
            "lastRunTs": GoogleProtobufTimestamp.from_dict(obj["lastRunTs"]) if obj.get("lastRunTs") is not None else None,
            "nextRunTs": GoogleProtobufTimestamp.from_dict(obj["nextRunTs"]) if obj.get("nextRunTs") is not None else None,
            "numDevices": obj.get("numDevices"),
            "rolloutConfig": UpgradeRolloutConfig.from_dict(obj["rolloutConfig"]) if obj.get("rolloutConfig") is not None else None,
            "status": obj.get("status")
        })
        return _obj


