# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from graphiant_sdk.models.upgrade_monthly_recurrence import UpgradeMonthlyRecurrence
from graphiant_sdk.models.upgrade_weekly_recurrence import UpgradeWeeklyRecurrence
from graphiant_sdk.models.upgrade_yearly_recurrence import UpgradeYearlyRecurrence
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpgradeRecurringSchedule(BaseModel):
    """
    UpgradeRecurringSchedule
    """ # noqa: E501
    monthly: Optional[UpgradeMonthlyRecurrence] = None
    starts_at_ts: GoogleProtobufTimestamp = Field(alias="startsAtTs")
    weekly: Optional[UpgradeWeeklyRecurrence] = None
    yearly: Optional[UpgradeYearlyRecurrence] = None
    __properties: ClassVar[List[str]] = ["monthly", "startsAtTs", "weekly", "yearly"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpgradeRecurringSchedule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of monthly
        if self.monthly:
            _dict['monthly'] = self.monthly.to_dict()
        # override the default output from pydantic by calling `to_dict()` of starts_at_ts
        if self.starts_at_ts:
            _dict['startsAtTs'] = self.starts_at_ts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of weekly
        if self.weekly:
            _dict['weekly'] = self.weekly.to_dict()
        # override the default output from pydantic by calling `to_dict()` of yearly
        if self.yearly:
            _dict['yearly'] = self.yearly.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpgradeRecurringSchedule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "monthly": UpgradeMonthlyRecurrence.from_dict(obj["monthly"]) if obj.get("monthly") is not None else None,
            "startsAtTs": GoogleProtobufTimestamp.from_dict(obj["startsAtTs"]) if obj.get("startsAtTs") is not None else None,
            "weekly": UpgradeWeeklyRecurrence.from_dict(obj["weekly"]) if obj.get("weekly") is not None else None,
            "yearly": UpgradeYearlyRecurrence.from_dict(obj["yearly"]) if obj.get("yearly") is not None else None
        })
        return _obj


