# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.common_billing_contract import CommonBillingContract
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1EnterprisesPutRequest(BaseModel):
    """
    V1EnterprisesPutRequest
    """ # noqa: E501
    account_type: StrictStr = Field(description=" (required)", alias="accountType", json_schema_extra={"examples": ["ENUM_VALUE"]})
    admin_email: Optional[StrictStr] = Field(default=None, alias="adminEmail", json_schema_extra={"examples": ["example string"]})
    admin_first_name: Optional[StrictStr] = Field(default=None, alias="adminFirstName", json_schema_extra={"examples": ["example string"]})
    admin_last_name: Optional[StrictStr] = Field(default=None, alias="adminLastName", json_schema_extra={"examples": ["example string"]})
    admin_time_zone: Optional[StrictStr] = Field(default=None, alias="adminTimeZone", json_schema_extra={"examples": ["example string"]})
    cloud_provider: Optional[StrictStr] = Field(default=None, alias="cloudProvider", json_schema_extra={"examples": ["ENUM_VALUE"]})
    company_name: StrictStr = Field(description=" (required)", alias="companyName", json_schema_extra={"examples": ["example string"]})
    credit_limit: Optional[StrictInt] = Field(default=None, alias="creditLimit", json_schema_extra={"examples": [123]})
    description: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    enterprise_contract: CommonBillingContract = Field(alias="enterpriseContract")
    logo: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    marketplace_id: Optional[StrictStr] = Field(default=None, alias="marketplaceId", json_schema_extra={"examples": ["example string"]})
    small_logo: Optional[StrictStr] = Field(default=None, alias="smallLogo", json_schema_extra={"examples": ["example string"]})
    __properties: ClassVar[List[str]] = ["accountType", "adminEmail", "adminFirstName", "adminLastName", "adminTimeZone", "cloudProvider", "companyName", "creditLimit", "description", "enterpriseContract", "logo", "marketplaceId", "smallLogo"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1EnterprisesPutRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of enterprise_contract
        if self.enterprise_contract:
            _dict['enterpriseContract'] = self.enterprise_contract.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1EnterprisesPutRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accountType": obj.get("accountType"),
            "adminEmail": obj.get("adminEmail"),
            "adminFirstName": obj.get("adminFirstName"),
            "adminLastName": obj.get("adminLastName"),
            "adminTimeZone": obj.get("adminTimeZone"),
            "cloudProvider": obj.get("cloudProvider"),
            "companyName": obj.get("companyName"),
            "creditLimit": obj.get("creditLimit"),
            "description": obj.get("description"),
            "enterpriseContract": CommonBillingContract.from_dict(obj["enterpriseContract"]) if obj.get("enterpriseContract") is not None else None,
            "logo": obj.get("logo"),
            "marketplaceId": obj.get("marketplaceId"),
            "smallLogo": obj.get("smallLogo")
        })
        return _obj


