# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1GlobalLanSegmentsGetResponseEntry(BaseModel):
    """
    V1GlobalLanSegmentsGetResponseEntry
    """ # noqa: E501
    associated_interfaces: Optional[StrictInt] = Field(default=None, alias="associatedInterfaces", json_schema_extra={"examples": [123]})
    created_at: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="createdAt")
    description: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    edge_references: Optional[StrictInt] = Field(default=None, alias="edgeReferences", json_schema_extra={"examples": [123]})
    id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1234567891011]})
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["example string"]})
    site_list_references: Optional[StrictInt] = Field(default=None, alias="siteListReferences", json_schema_extra={"examples": [123]})
    __properties: ClassVar[List[str]] = ["associatedInterfaces", "createdAt", "description", "edgeReferences", "id", "name", "siteListReferences"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1GlobalLanSegmentsGetResponseEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_at
        if self.created_at:
            _dict['createdAt'] = self.created_at.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1GlobalLanSegmentsGetResponseEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "associatedInterfaces": obj.get("associatedInterfaces"),
            "createdAt": GoogleProtobufTimestamp.from_dict(obj["createdAt"]) if obj.get("createdAt") is not None else None,
            "description": obj.get("description"),
            "edgeReferences": obj.get("edgeReferences"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "siteListReferences": obj.get("siteListReferences")
        })
        return _obj


