# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from graphiant_sdk.models.common_billing_contract import CommonBillingContract
from graphiant_sdk.models.mana_v2_managed_enterprise_contract_info import ManaV2ManagedEnterpriseContractInfo
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1MspManagedEnterpriseContractInfoGetResponse(BaseModel):
    """
    V1MspManagedEnterpriseContractInfoGetResponse
    """ # noqa: E501
    enterprises: Optional[List[ManaV2ManagedEnterpriseContractInfo]] = None
    msp_consumed_credits: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="All credits consumed by the MSP over the entirety of its contracts", alias="mspConsumedCredits", json_schema_extra={"examples": [12.34]})
    msp_contract: Optional[CommonBillingContract] = Field(default=None, alias="mspContract")
    __properties: ClassVar[List[str]] = ["enterprises", "mspConsumedCredits", "mspContract"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1MspManagedEnterpriseContractInfoGetResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in enterprises (list)
        _items = []
        if self.enterprises:
            for _item_enterprises in self.enterprises:
                if _item_enterprises:
                    _items.append(_item_enterprises.to_dict())
            _dict['enterprises'] = _items
        # override the default output from pydantic by calling `to_dict()` of msp_contract
        if self.msp_contract:
            _dict['mspContract'] = self.msp_contract.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1MspManagedEnterpriseContractInfoGetResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enterprises": [ManaV2ManagedEnterpriseContractInfo.from_dict(_item) for _item in obj["enterprises"]] if obj.get("enterprises") is not None else None,
            "mspConsumedCredits": obj.get("mspConsumedCredits"),
            "mspContract": CommonBillingContract.from_dict(obj["mspContract"]) if obj.get("mspContract") is not None else None
        })
        return _obj


