# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.mana_v2_bgp_neighbor import ManaV2BgpNeighbor
from graphiant_sdk.models.mana_v2_public_vif_gateway_consumer_lan_devices import ManaV2PublicVifGatewayConsumerLanDevices
from graphiant_sdk.models.mana_v2_public_vif_gateway_nat_prefix_strategy import ManaV2PublicVifGatewayNatPrefixStrategy
from graphiant_sdk.models.mana_v2_site_information import ManaV2SiteInformation
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1PvifIdDetailsGetResponse(BaseModel):
    """
    V1PvifIdDetailsGetResponse
    """ # noqa: E501
    advertise_all_sites: Optional[StrictBool] = Field(default=None, description="True when consumer scope is all symmetric sites (snapshotted on create and update); false when advertisement lists explicit sites or site lists", alias="advertiseAllSites", json_schema_extra={"examples": [True]})
    advertisement: Optional[ManaV2SiteInformation] = None
    consumer_lan_segments: Optional[Dict[str, ManaV2PublicVifGatewayConsumerLanDevices]] = Field(default=None, alias="consumerLanSegments")
    covering_prefixes: Optional[List[StrictStr]] = Field(default=None, alias="coveringPrefixes")
    gateway_bgp_neighbors: Optional[Dict[str, ManaV2BgpNeighbor]] = Field(default=None, alias="gatewayBgpNeighbors")
    id: Optional[StrictInt] = Field(default=None, description="Producer service id", json_schema_extra={"examples": [1234567891011]})
    lan_segment_id: Optional[StrictInt] = Field(default=None, description="Producer LAN segment (VRF) id", alias="lanSegmentId", json_schema_extra={"examples": [1234567891011]})
    nat_prefix_strategy: Optional[ManaV2PublicVifGatewayNatPrefixStrategy] = Field(default=None, alias="natPrefixStrategy")
    region_id: Optional[StrictInt] = Field(default=None, description="Graphiant region for gateway appliances", alias="regionId", json_schema_extra={"examples": [123]})
    service_name: Optional[StrictStr] = Field(default=None, description="Service display name", alias="serviceName", json_schema_extra={"examples": ["example string"]})
    storage_provider: Optional[StrictStr] = Field(default=None, description="Storage provider for gateway appliances", alias="storageProvider", json_schema_extra={"examples": ["ENUM_VALUE"]})
    __properties: ClassVar[List[str]] = ["advertiseAllSites", "advertisement", "consumerLanSegments", "coveringPrefixes", "gatewayBgpNeighbors", "id", "lanSegmentId", "natPrefixStrategy", "regionId", "serviceName", "storageProvider"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1PvifIdDetailsGetResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of advertisement
        if self.advertisement:
            _dict['advertisement'] = self.advertisement.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in consumer_lan_segments (dict)
        _field_dict = {}
        if self.consumer_lan_segments:
            for _key_consumer_lan_segments in self.consumer_lan_segments:
                if self.consumer_lan_segments[_key_consumer_lan_segments]:
                    _field_dict[_key_consumer_lan_segments] = self.consumer_lan_segments[_key_consumer_lan_segments].to_dict()
            _dict['consumerLanSegments'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in gateway_bgp_neighbors (dict)
        _field_dict = {}
        if self.gateway_bgp_neighbors:
            for _key_gateway_bgp_neighbors in self.gateway_bgp_neighbors:
                if self.gateway_bgp_neighbors[_key_gateway_bgp_neighbors]:
                    _field_dict[_key_gateway_bgp_neighbors] = self.gateway_bgp_neighbors[_key_gateway_bgp_neighbors].to_dict()
            _dict['gatewayBgpNeighbors'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of nat_prefix_strategy
        if self.nat_prefix_strategy:
            _dict['natPrefixStrategy'] = self.nat_prefix_strategy.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1PvifIdDetailsGetResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "advertiseAllSites": obj.get("advertiseAllSites"),
            "advertisement": ManaV2SiteInformation.from_dict(obj["advertisement"]) if obj.get("advertisement") is not None else None,
            "consumerLanSegments": dict(
                (_k, ManaV2PublicVifGatewayConsumerLanDevices.from_dict(_v))
                for _k, _v in obj["consumerLanSegments"].items()
            )
            if obj.get("consumerLanSegments") is not None
            else None,
            "coveringPrefixes": obj.get("coveringPrefixes"),
            "gatewayBgpNeighbors": dict(
                (_k, ManaV2BgpNeighbor.from_dict(_v))
                for _k, _v in obj["gatewayBgpNeighbors"].items()
            )
            if obj.get("gatewayBgpNeighbors") is not None
            else None,
            "id": obj.get("id"),
            "lanSegmentId": obj.get("lanSegmentId"),
            "natPrefixStrategy": ManaV2PublicVifGatewayNatPrefixStrategy.from_dict(obj["natPrefixStrategy"]) if obj.get("natPrefixStrategy") is not None else None,
            "regionId": obj.get("regionId"),
            "serviceName": obj.get("serviceName"),
            "storageProvider": obj.get("storageProvider")
        })
        return _obj


